//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public abstract partial class AnonymousFunctionExpressionSyntax : ExpressionSyntax
    {
        internal AnonymousFunctionExpressionSyntax()
        {
        }

        public abstract SyntaxToken AsyncKeyword { get; }
        public abstract BlockSyntax? Block { get; }

        public CSharpSyntaxNode Body
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public abstract ExpressionSyntax? ExpressionBody { get; }
        public abstract SyntaxTokenList Modifiers { get; }

        public AnonymousFunctionExpressionSyntax AddBlockAttributeLists(params AttributeListSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax AddBlockStatements(params StatementSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax AddModifiers(params SyntaxToken[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax WithAsyncKeyword(SyntaxToken asyncKeyword)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax WithBlock(BlockSyntax? block)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax WithBody(CSharpSyntaxNode body)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax WithExpressionBody(ExpressionSyntax? expressionBody)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AnonymousFunctionExpressionSyntax WithModifiers(SyntaxTokenList modifiers)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.IAnonymousFunctionExpressionSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal AnonymousFunctionExpressionSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IAnonymousFunctionExpressionSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IAnonymousFunctionExpressionSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        private sealed partial class __AnalyzeAotProxy : AnonymousFunctionExpressionSyntax
        {
            internal __AnalyzeAotProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IAnonymousFunctionExpressionSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
            {
            }

            public override SyntaxToken AsyncKeyword
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override BlockSyntax? Block
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override ExpressionSyntax? ExpressionBody
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxTokenList Modifiers
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override void Accept(CSharpSyntaxVisitor visitor)
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }

            public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
                where TResult : default
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        internal static AnonymousFunctionExpressionSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new __AnalyzeAotProxy(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetAnonymousFunctionExpressionSyntaxVtbl(controlVtbl), handle);
    }
}
