//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface AttributeSyntax : CSharpSyntaxNode
    {
        public AttributeArgumentListSyntax? ArgumentList
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.AttributeSyntax_get_ArgumentList(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : AttributeArgumentListSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public NameSyntax Name
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.AttributeSyntax_get_Name(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return NameSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.AttributeSyntax_Accept_2b308687(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AttributeSyntax AddArgumentListArguments(params AttributeArgumentSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public AttributeSyntax Update(NameSyntax name, AttributeArgumentListSyntax? argumentList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.AttributeSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), argumentList is null ? 0L : argumentList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public AttributeSyntax WithArgumentList(AttributeArgumentListSyntax? argumentList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.AttributeSyntax_WithArgumentList(__AnalyzeAotGetHandle(controlVtbl), argumentList is null ? 0L : argumentList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public AttributeSyntax WithName(NameSyntax name)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IAttributeSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.AttributeSyntax_WithName(__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.RoslynFacade.RoslynObjectProxy __AnalyzeAotGetProxy() => (global::AnalyzeAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::AnalyzeAot.Abi.IAttributeSyntaxVtbl __AnalyzeAotGetVtbl() => global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetAttributeSyntaxVtbl(__AnalyzeAotGetControlVtbl());
        public global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __AnalyzeAotGetProxy().ControlVtbl;
        public long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl) => __AnalyzeAotGetProxy().GetHandle(controlVtbl);
        internal static AttributeSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (AttributeSyntax)(object)new global::AnalyzeAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("98b58147-c04f-561c-8daf-cb853da4585e")]
        internal partial interface __AnalyzeAotImplementation : AttributeSyntax
        {
        }
    }
}
