//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public sealed partial class BinaryExpressionSyntax : ExpressionSyntax
    {
        internal BinaryExpressionSyntax()
        {
        }

        public ExpressionSyntax Left
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public SyntaxToken OperatorToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.BinaryExpressionSyntax_get_OperatorToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public ExpressionSyntax Right
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public override void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.BinaryExpressionSyntax_Accept_7b26e968(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
            where TResult : default
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public BinaryExpressionSyntax Update(ExpressionSyntax left, SyntaxToken operatorToken, ExpressionSyntax right)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.BinaryExpressionSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), left.__AnalyzeAotGetHandle(controlVtbl), operatorToken.__AnalyzeAotGetHandle(controlVtbl), right.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public BinaryExpressionSyntax WithLeft(ExpressionSyntax left)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.BinaryExpressionSyntax_WithLeft(__AnalyzeAotGetHandle(controlVtbl), left.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public BinaryExpressionSyntax WithOperatorToken(SyntaxToken operatorToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.BinaryExpressionSyntax_WithOperatorToken(__AnalyzeAotGetHandle(controlVtbl), operatorToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public BinaryExpressionSyntax WithRight(ExpressionSyntax right)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.BinaryExpressionSyntax_WithRight(__AnalyzeAotGetHandle(controlVtbl), right.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal BinaryExpressionSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IBinaryExpressionSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static BinaryExpressionSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new BinaryExpressionSyntax(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetBinaryExpressionSyntaxVtbl(controlVtbl), handle);
    }
}
