//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public abstract partial class CommonForEachStatementSyntax : StatementSyntax
    {
        internal CommonForEachStatementSyntax()
        {
        }

        public abstract SyntaxToken AwaitKeyword { get; }
        public abstract SyntaxToken CloseParenToken { get; }
        public abstract ExpressionSyntax Expression { get; }
        public abstract SyntaxToken ForEachKeyword { get; }
        public abstract SyntaxToken InKeyword { get; }
        public abstract SyntaxToken OpenParenToken { get; }
        public abstract StatementSyntax Statement { get; }

        public new CommonForEachStatementSyntax AddAttributeLists(params AttributeListSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new CommonForEachStatementSyntax WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithAwaitKeyword(SyntaxToken awaitKeyword)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithCloseParenToken(SyntaxToken closeParenToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithExpression(ExpressionSyntax expression)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithForEachKeyword(SyntaxToken forEachKeyword)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithInKeyword(SyntaxToken inKeyword)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithOpenParenToken(SyntaxToken openParenToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public CommonForEachStatementSyntax WithStatement(StatementSyntax statement)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.ICommonForEachStatementSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal CommonForEachStatementSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.ICommonForEachStatementSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.ICommonForEachStatementSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        private sealed partial class __AnalyzeAotProxy : CommonForEachStatementSyntax
        {
            internal __AnalyzeAotProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.ICommonForEachStatementSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
            {
            }

            public override SyntaxToken AwaitKeyword
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxToken CloseParenToken
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override ExpressionSyntax Expression
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxToken ForEachKeyword
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxToken InKeyword
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxToken OpenParenToken
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override StatementSyntax Statement
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override SyntaxList<AttributeListSyntax> AttributeLists
            {
                get
                {
                    throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
                }
            }

            public override void Accept(CSharpSyntaxVisitor visitor)
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }

            public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
                where TResult : default
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        internal static CommonForEachStatementSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new __AnalyzeAotProxy(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetCommonForEachStatementSyntaxVtbl(controlVtbl), handle);
    }
}
