//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface DelegateDeclarationSyntax : MemberDeclarationSyntax
    {
        public int Arity
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_Arity(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result;
            }
        }

        public SyntaxList<AttributeListSyntax> AttributeLists
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public SyntaxList<TypeParameterConstraintClauseSyntax> ConstraintClauses
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public SyntaxToken DelegateKeyword
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_DelegateKeyword(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken Identifier
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_Identifier(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxTokenList Modifiers
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_Modifiers(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxTokenList.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public ParameterListSyntax ParameterList
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_ParameterList(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return ParameterListSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public TypeSyntax ReturnType
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_ReturnType(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return TypeSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken SemicolonToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_SemicolonToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public TypeParameterListSyntax? TypeParameterList
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.DelegateDeclarationSyntax_get_TypeParameterList(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : TypeParameterListSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_Accept_65ed7181(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new DelegateDeclarationSyntax AddAttributeLists(params AttributeListSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax AddConstraintClauses(params TypeParameterConstraintClauseSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new DelegateDeclarationSyntax AddModifiers(params SyntaxToken[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax AddParameterListParameters(params ParameterSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax AddTypeParameterListParameters(params TypeParameterSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax Update(SyntaxList<AttributeListSyntax> attributeLists, SyntaxTokenList modifiers, SyntaxToken delegateKeyword, TypeSyntax returnType, SyntaxToken identifier, TypeParameterListSyntax? typeParameterList, ParameterListSyntax parameterList, SyntaxList<TypeParameterConstraintClauseSyntax> constraintClauses, SyntaxToken semicolonToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new DelegateDeclarationSyntax WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax WithConstraintClauses(SyntaxList<TypeParameterConstraintClauseSyntax> constraintClauses)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public DelegateDeclarationSyntax WithDelegateKeyword(SyntaxToken delegateKeyword)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithDelegateKeyword(__AnalyzeAotGetHandle(controlVtbl), delegateKeyword.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public DelegateDeclarationSyntax WithIdentifier(SyntaxToken identifier)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithIdentifier(__AnalyzeAotGetHandle(controlVtbl), identifier.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new DelegateDeclarationSyntax WithModifiers(SyntaxTokenList modifiers)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithModifiers(__AnalyzeAotGetHandle(controlVtbl), modifiers.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public DelegateDeclarationSyntax WithParameterList(ParameterListSyntax parameterList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithParameterList(__AnalyzeAotGetHandle(controlVtbl), parameterList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public DelegateDeclarationSyntax WithReturnType(TypeSyntax returnType)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithReturnType(__AnalyzeAotGetHandle(controlVtbl), returnType.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public DelegateDeclarationSyntax WithSemicolonToken(SyntaxToken semicolonToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithSemicolonToken(__AnalyzeAotGetHandle(controlVtbl), semicolonToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public DelegateDeclarationSyntax WithTypeParameterList(TypeParameterListSyntax? typeParameterList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.DelegateDeclarationSyntax_WithTypeParameterList(__AnalyzeAotGetHandle(controlVtbl), typeParameterList is null ? 0L : typeParameterList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.RoslynFacade.RoslynObjectProxy __AnalyzeAotGetProxy() => (global::AnalyzeAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::AnalyzeAot.Abi.IDelegateDeclarationSyntaxVtbl __AnalyzeAotGetVtbl() => global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetDelegateDeclarationSyntaxVtbl(__AnalyzeAotGetControlVtbl());
        public global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __AnalyzeAotGetProxy().ControlVtbl;
        public long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl) => __AnalyzeAotGetProxy().GetHandle(controlVtbl);
        internal static DelegateDeclarationSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (DelegateDeclarationSyntax)(object)new global::AnalyzeAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("5e2cd2a6-8254-5876-957a-4fdb4cb0977e")]
        internal partial interface __AnalyzeAotImplementation : DelegateDeclarationSyntax
        {
        }
    }
}
