//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface EndIfDirectiveTriviaSyntax : DirectiveTriviaSyntax
    {
        public SyntaxToken EndIfKeyword
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.EndIfDirectiveTriviaSyntax_get_EndIfKeyword(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken EndOfDirectiveToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.EndIfDirectiveTriviaSyntax_get_EndOfDirectiveToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken HashToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.EndIfDirectiveTriviaSyntax_get_HashToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public bool IsActive
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.EndIfDirectiveTriviaSyntax_get_IsActive(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_Accept_563db3d2(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public EndIfDirectiveTriviaSyntax Update(SyntaxToken hashToken, SyntaxToken endIfKeyword, SyntaxToken endOfDirectiveToken, bool isActive)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), hashToken.__AnalyzeAotGetHandle(controlVtbl), endIfKeyword.__AnalyzeAotGetHandle(controlVtbl), endOfDirectiveToken.__AnalyzeAotGetHandle(controlVtbl), isActive ? 1 : 0, out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public EndIfDirectiveTriviaSyntax WithEndIfKeyword(SyntaxToken endIfKeyword)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_WithEndIfKeyword(__AnalyzeAotGetHandle(controlVtbl), endIfKeyword.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new EndIfDirectiveTriviaSyntax WithEndOfDirectiveToken(SyntaxToken endOfDirectiveToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_WithEndOfDirectiveToken(__AnalyzeAotGetHandle(controlVtbl), endOfDirectiveToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new EndIfDirectiveTriviaSyntax WithHashToken(SyntaxToken hashToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_WithHashToken(__AnalyzeAotGetHandle(controlVtbl), hashToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public EndIfDirectiveTriviaSyntax WithIsActive(bool isActive)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.EndIfDirectiveTriviaSyntax_WithIsActive(__AnalyzeAotGetHandle(controlVtbl), isActive ? 1 : 0, out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.RoslynFacade.RoslynObjectProxy __AnalyzeAotGetProxy() => (global::AnalyzeAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::AnalyzeAot.Abi.IEndIfDirectiveTriviaSyntaxVtbl __AnalyzeAotGetVtbl() => global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetEndIfDirectiveTriviaSyntaxVtbl(__AnalyzeAotGetControlVtbl());
        public global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __AnalyzeAotGetProxy().ControlVtbl;
        public long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl) => __AnalyzeAotGetProxy().GetHandle(controlVtbl);
        internal static EndIfDirectiveTriviaSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (EndIfDirectiveTriviaSyntax)(object)new global::AnalyzeAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("b356e193-1205-5fbf-9494-1e8cd42d1991")]
        internal partial interface __AnalyzeAotImplementation : EndIfDirectiveTriviaSyntax
        {
        }
    }
}
