//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public sealed partial class IndexerDeclarationSyntax : BasePropertyDeclarationSyntax
    {
        internal IndexerDeclarationSyntax()
        {
        }

        public override AccessorListSyntax? AccessorList
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_AccessorList(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : AccessorListSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public override SyntaxList<AttributeListSyntax> AttributeLists
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public override ExplicitInterfaceSpecifierSyntax? ExplicitInterfaceSpecifier
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_ExplicitInterfaceSpecifier(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : ExplicitInterfaceSpecifierSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public ArrowExpressionClauseSyntax? ExpressionBody
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_ExpressionBody(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : ArrowExpressionClauseSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public override SyntaxTokenList Modifiers
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_Modifiers(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxTokenList.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public BracketedParameterListSyntax ParameterList
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_ParameterList(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return BracketedParameterListSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Obsolete("This member is obsolete.", true)]
        public SyntaxToken Semicolon
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public SyntaxToken SemicolonToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_SemicolonToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken ThisKeyword
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.IndexerDeclarationSyntax_get_ThisKeyword(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public override TypeSyntax Type
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public override void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_Accept_826595c1(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
            where TResult : default
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new IndexerDeclarationSyntax AddAccessorListAccessors(params AccessorDeclarationSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new IndexerDeclarationSyntax AddAttributeLists(params AttributeListSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new IndexerDeclarationSyntax AddModifiers(params SyntaxToken[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public IndexerDeclarationSyntax AddParameterListParameters(params ParameterSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public IndexerDeclarationSyntax Update(SyntaxList<AttributeListSyntax> attributeLists, SyntaxTokenList modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax? explicitInterfaceSpecifier, SyntaxToken thisKeyword, BracketedParameterListSyntax parameterList, AccessorListSyntax? accessorList, ArrowExpressionClauseSyntax? expressionBody, SyntaxToken semicolonToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new IndexerDeclarationSyntax WithAccessorList(AccessorListSyntax? accessorList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithAccessorList(__AnalyzeAotGetHandle(controlVtbl), accessorList is null ? 0L : accessorList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new IndexerDeclarationSyntax WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public new IndexerDeclarationSyntax WithExplicitInterfaceSpecifier(ExplicitInterfaceSpecifierSyntax? explicitInterfaceSpecifier)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithExplicitInterfaceSpecifier(__AnalyzeAotGetHandle(controlVtbl), explicitInterfaceSpecifier is null ? 0L : explicitInterfaceSpecifier.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public IndexerDeclarationSyntax WithExpressionBody(ArrowExpressionClauseSyntax? expressionBody)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithExpressionBody(__AnalyzeAotGetHandle(controlVtbl), expressionBody is null ? 0L : expressionBody.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new IndexerDeclarationSyntax WithModifiers(SyntaxTokenList modifiers)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithModifiers(__AnalyzeAotGetHandle(controlVtbl), modifiers.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public IndexerDeclarationSyntax WithParameterList(BracketedParameterListSyntax parameterList)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithParameterList(__AnalyzeAotGetHandle(controlVtbl), parameterList.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Obsolete("This member is obsolete.", true)]
        public IndexerDeclarationSyntax WithSemicolon(SyntaxToken semicolon)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public IndexerDeclarationSyntax WithSemicolonToken(SyntaxToken semicolonToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithSemicolonToken(__AnalyzeAotGetHandle(controlVtbl), semicolonToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public IndexerDeclarationSyntax WithThisKeyword(SyntaxToken thisKeyword)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithThisKeyword(__AnalyzeAotGetHandle(controlVtbl), thisKeyword.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new IndexerDeclarationSyntax WithType(TypeSyntax type)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.IndexerDeclarationSyntax_WithType(__AnalyzeAotGetHandle(controlVtbl), @type.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal IndexerDeclarationSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IIndexerDeclarationSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static IndexerDeclarationSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new IndexerDeclarationSyntax(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetIndexerDeclarationSyntaxVtbl(controlVtbl), handle);
    }
}
