//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public sealed partial class InitializerExpressionSyntax : ExpressionSyntax
    {
        internal InitializerExpressionSyntax()
        {
        }

        public SyntaxToken CloseBraceToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.InitializerExpressionSyntax_get_CloseBraceToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SeparatedSyntaxList<ExpressionSyntax> Expressions
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public SyntaxToken OpenBraceToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.InitializerExpressionSyntax_get_OpenBraceToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public override void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.InitializerExpressionSyntax_Accept_9e69839b(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
            where TResult : default
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public InitializerExpressionSyntax AddExpressions(params ExpressionSyntax[] items)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public InitializerExpressionSyntax Update(SyntaxToken openBraceToken, SeparatedSyntaxList<ExpressionSyntax> expressions, SyntaxToken closeBraceToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public InitializerExpressionSyntax WithCloseBraceToken(SyntaxToken closeBraceToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.InitializerExpressionSyntax_WithCloseBraceToken(__AnalyzeAotGetHandle(controlVtbl), closeBraceToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public InitializerExpressionSyntax WithExpressions(SeparatedSyntaxList<ExpressionSyntax> expressions)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public InitializerExpressionSyntax WithOpenBraceToken(SyntaxToken openBraceToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.InitializerExpressionSyntax_WithOpenBraceToken(__AnalyzeAotGetHandle(controlVtbl), openBraceToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal InitializerExpressionSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IInitializerExpressionSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static InitializerExpressionSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new InitializerExpressionSyntax(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetInitializerExpressionSyntaxVtbl(controlVtbl), handle);
    }
}
