//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface LoadDirectiveTriviaSyntax : DirectiveTriviaSyntax
    {
        public SyntaxToken EndOfDirectiveToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.LoadDirectiveTriviaSyntax_get_EndOfDirectiveToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken File
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.LoadDirectiveTriviaSyntax_get_File(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken HashToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.LoadDirectiveTriviaSyntax_get_HashToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public bool IsActive
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.LoadDirectiveTriviaSyntax_get_IsActive(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public SyntaxToken LoadKeyword
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.LoadDirectiveTriviaSyntax_get_LoadKeyword(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_Accept_84136757(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public LoadDirectiveTriviaSyntax Update(SyntaxToken hashToken, SyntaxToken loadKeyword, SyntaxToken file, SyntaxToken endOfDirectiveToken, bool isActive)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), hashToken.__AnalyzeAotGetHandle(controlVtbl), loadKeyword.__AnalyzeAotGetHandle(controlVtbl), @file.__AnalyzeAotGetHandle(controlVtbl), endOfDirectiveToken.__AnalyzeAotGetHandle(controlVtbl), isActive ? 1 : 0, out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new LoadDirectiveTriviaSyntax WithEndOfDirectiveToken(SyntaxToken endOfDirectiveToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_WithEndOfDirectiveToken(__AnalyzeAotGetHandle(controlVtbl), endOfDirectiveToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public LoadDirectiveTriviaSyntax WithFile(SyntaxToken file)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_WithFile(__AnalyzeAotGetHandle(controlVtbl), @file.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public new LoadDirectiveTriviaSyntax WithHashToken(SyntaxToken hashToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_WithHashToken(__AnalyzeAotGetHandle(controlVtbl), hashToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public LoadDirectiveTriviaSyntax WithIsActive(bool isActive)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_WithIsActive(__AnalyzeAotGetHandle(controlVtbl), isActive ? 1 : 0, out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public LoadDirectiveTriviaSyntax WithLoadKeyword(SyntaxToken loadKeyword)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.LoadDirectiveTriviaSyntax_WithLoadKeyword(__AnalyzeAotGetHandle(controlVtbl), loadKeyword.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.RoslynFacade.RoslynObjectProxy __AnalyzeAotGetProxy() => (global::AnalyzeAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::AnalyzeAot.Abi.ILoadDirectiveTriviaSyntaxVtbl __AnalyzeAotGetVtbl() => global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetLoadDirectiveTriviaSyntaxVtbl(__AnalyzeAotGetControlVtbl());
        public global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __AnalyzeAotGetProxy().ControlVtbl;
        public long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl) => __AnalyzeAotGetProxy().GetHandle(controlVtbl);
        internal static LoadDirectiveTriviaSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (LoadDirectiveTriviaSyntax)(object)new global::AnalyzeAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("e6d4828f-aac9-5b86-ab22-982eb560245c")]
        internal partial interface __AnalyzeAotImplementation : LoadDirectiveTriviaSyntax
        {
        }
    }
}
