//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface MemberBindingExpressionSyntax : ExpressionSyntax
    {
        public SimpleNameSyntax Name
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.MemberBindingExpressionSyntax_get_Name(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SimpleNameSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken OperatorToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.MemberBindingExpressionSyntax_get_OperatorToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.MemberBindingExpressionSyntax_Accept_efdd4519(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public MemberBindingExpressionSyntax Update(SyntaxToken operatorToken, SimpleNameSyntax name)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.MemberBindingExpressionSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), operatorToken.__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public MemberBindingExpressionSyntax WithName(SimpleNameSyntax name)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.MemberBindingExpressionSyntax_WithName(__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public MemberBindingExpressionSyntax WithOperatorToken(SyntaxToken operatorToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.MemberBindingExpressionSyntax_WithOperatorToken(__AnalyzeAotGetHandle(controlVtbl), operatorToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.RoslynFacade.RoslynObjectProxy __AnalyzeAotGetProxy() => (global::AnalyzeAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::AnalyzeAot.Abi.IMemberBindingExpressionSyntaxVtbl __AnalyzeAotGetVtbl() => global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetMemberBindingExpressionSyntaxVtbl(__AnalyzeAotGetControlVtbl());
        public global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __AnalyzeAotGetProxy().ControlVtbl;
        public long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl) => __AnalyzeAotGetProxy().GetHandle(controlVtbl);
        internal static MemberBindingExpressionSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (MemberBindingExpressionSyntax)(object)new global::AnalyzeAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("4a7643b6-9daf-5150-8f12-08446f40a855")]
        internal partial interface __AnalyzeAotImplementation : MemberBindingExpressionSyntax
        {
        }
    }
}
