//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public sealed partial class NameEqualsSyntax : CSharpSyntaxNode
    {
        internal NameEqualsSyntax()
        {
        }

        public SyntaxToken EqualsToken
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.NameEqualsSyntax_get_EqualsToken(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public IdentifierNameSyntax Name
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.NameEqualsSyntax_get_Name(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return IdentifierNameSyntax.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public override void Accept(CSharpSyntaxVisitor visitor)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.NameEqualsSyntax_Accept_66336c64(__AnalyzeAotGetHandle(controlVtbl), visitor.__AnalyzeAotGetHandle(controlVtbl));
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public override TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
            where TResult : default
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public NameEqualsSyntax Update(IdentifierNameSyntax name, SyntaxToken equalsToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.NameEqualsSyntax_Update(__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), equalsToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public NameEqualsSyntax WithEqualsToken(SyntaxToken equalsToken)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.NameEqualsSyntax_WithEqualsToken(__AnalyzeAotGetHandle(controlVtbl), equalsToken.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        public NameEqualsSyntax WithName(IdentifierNameSyntax name)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
            global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl = __AnalyzeAotGetVtbl();
            int status = vtbl.NameEqualsSyntax_WithName(__AnalyzeAotGetHandle(controlVtbl), name.__AnalyzeAotGetHandle(controlVtbl), out long result);
            global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __AnalyzeAotCreateProxy(controlVtbl, result);
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal NameEqualsSyntax(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.INameEqualsSyntaxVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static NameEqualsSyntax __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new NameEqualsSyntax(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetNameEqualsSyntaxVtbl(controlVtbl), handle);
    }
}
