//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis
{
    public readonly partial struct CommandLineResource
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public string FullPath
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                long __analyzeAotReceiver = __AnalyzeAotGetHandle(controlVtbl);
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.CommandLineResource_get_FullPath(__analyzeAotReceiver, buffer, bufferLength, out requiredLength))!;
            }
        }

        public bool IsEmbedded
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.CommandLineResource_get_IsEmbedded(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, "LinkedResourceFileName")]
        public bool IsLinked
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.CommandLineResource_get_IsLinked(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public bool IsPublic
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.CommandLineResource_get_IsPublic(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public string? LinkedResourceFileName
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                long __analyzeAotReceiver = __AnalyzeAotGetHandle(controlVtbl);
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.CommandLineResource_get_LinkedResourceFileName(__analyzeAotReceiver, buffer, bufferLength, out requiredLength));
            }
        }

        public string ResourceName
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl = __AnalyzeAotGetVtbl();
                long __analyzeAotReceiver = __AnalyzeAotGetHandle(controlVtbl);
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.CommandLineResource_get_ResourceName(__analyzeAotReceiver, buffer, bufferLength, out requiredLength))!;
            }
        }

        private readonly global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private readonly global::AnalyzeAot.Abi.ICommandLineResourceVtbl? __analyzeAotVtbl;
        private readonly long __analyzeAotHandle;
        internal CommandLineResource(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.ICommandLineResourceVtbl vtbl, long handle)
        {
            this = default;
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.ICommandLineResourceVtbl __AnalyzeAotGetVtbl()
        {
            if (__analyzeAotVtbl is not null)
                return __analyzeAotVtbl;
            if (__analyzeAotHandle == 0)
                return global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetCommandLineResourceVtbl(global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl());
            throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        }

        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl()
        {
            if (__analyzeAotControlVtbl is not null)
                return __analyzeAotControlVtbl;
            if (__analyzeAotHandle == 0)
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl();
            throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        }

        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static CommandLineResource __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new CommandLineResource(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetCommandLineResourceVtbl(controlVtbl), handle);
    }
}
