//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis
{
    public readonly partial struct GeneratedSourceResult
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public string HintName
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl vtbl = __AnalyzeAotGetVtbl();
                long __analyzeAotReceiver = __AnalyzeAotGetHandle(controlVtbl);
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf8String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.GeneratedSourceResult_get_HintName(__analyzeAotReceiver, buffer, bufferLength, out requiredLength))!;
            }
        }

        public Text.SourceText SourceText
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.GeneratedSourceResult_get_SourceText(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return Text.SourceText.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxTree SyntaxTree
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.GeneratedSourceResult_get_SyntaxTree(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxTree.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        private readonly global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private readonly global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl? __analyzeAotVtbl;
        private readonly long __analyzeAotHandle;
        internal GeneratedSourceResult(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl vtbl, long handle)
        {
            this = default;
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IGeneratedSourceResultVtbl __AnalyzeAotGetVtbl()
        {
            if (__analyzeAotVtbl is not null)
                return __analyzeAotVtbl;
            if (__analyzeAotHandle == 0)
                return global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetGeneratedSourceResultVtbl(global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl());
            throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        }

        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl()
        {
            if (__analyzeAotControlVtbl is not null)
                return __analyzeAotControlVtbl;
            if (__analyzeAotHandle == 0)
                return global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl();
            throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        }

        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        internal static GeneratedSourceResult __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new GeneratedSourceResult(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetGeneratedSourceResultVtbl(controlVtbl), handle);
    }
}
