//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class AssemblyMetadataTypeVtblDispatcher : IAssemblyMetadataTypeVtbl
{
    private readonly RoslynInterop _owner;

    public AssemblyMetadataTypeVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int AssemblyMetadata_CreateFromFile(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string path,
        out long result)
    {
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::Microsoft.CodeAnalysis.AssemblyMetadata.CreateFromFile(path));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int AssemblyMetadata_Create_7ba6a262(
        long @module,
        out long result)
    {
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::Microsoft.CodeAnalysis.AssemblyMetadata.Create(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.ModuleMetadata>(@module)));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int AssemblyMetadata_Create_f1a4ccc3(
        long modules,
        out long result)
    {
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::Microsoft.CodeAnalysis.AssemblyMetadata.Create(global::System.Array.ConvertAll(_owner.Objects.GetObject<object[]>(modules), static value => (global::Microsoft.CodeAnalysis.ModuleMetadata)value)));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
