//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class CommandLineAnalyzerReferenceTypeVtblDispatcher : ICommandLineAnalyzerReferenceTypeVtbl
{
    private readonly RoslynInterop _owner;

    public CommandLineAnalyzerReferenceTypeVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int CommandLineAnalyzerReference_ctor(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string path,
        out long result)
    {
        RoslynCallCounters.Record(47);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(new global::Microsoft.CodeAnalysis.CommandLineAnalyzerReference(path));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
