//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class IDynamicInvocationOperationVtblDispatcher : IIDynamicInvocationOperationVtbl
{
    private readonly RoslynInterop _owner;

    public IDynamicInvocationOperationVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int IDynamicInvocationOperation_get_Arguments(
        long receiver,
        out long result)
    {
        RoslynCallCounters.Record(1047);
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::System.Linq.Enumerable.Cast<object>(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.Operations.IDynamicInvocationOperation>(receiver).Arguments).ToArray());
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int IDynamicInvocationOperation_get_Operation(
        long receiver,
        out long result)
    {
        RoslynCallCounters.Record(1048);
        result = default;

        try
        {
            result = _owner.Objects.AddObject(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.Operations.IDynamicInvocationOperation>(receiver).Operation);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
