//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class ISwitchCaseOperationVtblDispatcher : IISwitchCaseOperationVtbl
{
    private readonly RoslynInterop _owner;

    public ISwitchCaseOperationVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int ISwitchCaseOperation_get_Body(
        long receiver,
        out long result)
    {
        RoslynCallCounters.Record(1101);
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::System.Linq.Enumerable.Cast<object>(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.Operations.ISwitchCaseOperation>(receiver).Body).ToArray());
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int ISwitchCaseOperation_get_Clauses(
        long receiver,
        out long result)
    {
        RoslynCallCounters.Record(1102);
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::System.Linq.Enumerable.Cast<object>(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.Operations.ISwitchCaseOperation>(receiver).Clauses).ToArray());
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int ISwitchCaseOperation_get_Locals(
        long receiver,
        out long result)
    {
        RoslynCallCounters.Record(1103);
        result = default;

        try
        {
            result = _owner.Objects.AddObject(global::System.Linq.Enumerable.Cast<object>(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.Operations.ISwitchCaseOperation>(receiver).Locals).ToArray());
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
