//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class SubsystemVersionTypeVtblDispatcher : ISubsystemVersionTypeVtbl
{
    private readonly RoslynInterop _owner;

    public SubsystemVersionTypeVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int SubsystemVersion_Create(
        int major,
        int minor,
        out long result)
    {
        RoslynCallCounters.Record(1450);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.Create(major, minor));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_None(
        out long result)
    {
        RoslynCallCounters.Record(1457);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.None);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_Windows2000(
        out long result)
    {
        RoslynCallCounters.Record(1458);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.Windows2000);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_Windows7(
        out long result)
    {
        RoslynCallCounters.Record(1459);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.Windows7);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_Windows8(
        out long result)
    {
        RoslynCallCounters.Record(1460);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.Windows8);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_WindowsVista(
        out long result)
    {
        RoslynCallCounters.Record(1461);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.WindowsVista);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int SubsystemVersion_get_WindowsXP(
        out long result)
    {
        RoslynCallCounters.Record(1462);
        result = default;

        try
        {
            result = _owner.Objects.AddValue(global::Microsoft.CodeAnalysis.SubsystemVersion.WindowsXP);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
