//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class SyntaxTreeOptionsProviderVtblDispatcher : ISyntaxTreeOptionsProviderVtbl
{
    private readonly RoslynInterop _owner;

    public SyntaxTreeOptionsProviderVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int SyntaxTreeOptionsProvider_IsGenerated(
        long receiver,
        long tree,
        long cancellationToken,
        out int result)
    {
        RoslynCallCounters.Record(5955);
        result = default;

        try
        {
            result = (int)_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.SyntaxTreeOptionsProvider>(receiver).IsGenerated(_owner.Objects.GetObject<global::Microsoft.CodeAnalysis.SyntaxTree>(tree), cancellationToken == 0 ? global::System.Threading.CancellationToken.None : _owner.Objects.GetObject<global::System.Threading.CancellationTokenSource>(cancellationToken).Token);
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
