//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Text;
using System.Runtime.InteropServices.Marshalling;
using RoslynAot.Abi;

namespace RoslynAot.Csc;

[GeneratedComClass]
internal sealed partial class TextSpanVtblDispatcher : ITextSpanVtbl
{
    private readonly RoslynInterop _owner;

    public TextSpanVtblDispatcher(RoslynInterop owner)
    {
        _owner = owner ?? throw new ArgumentNullException(nameof(owner));
    }

    public int TextSpan_CompareTo(
        long receiver,
        long other,
        out int result)
    {
        RoslynCallCounters.Record(1844);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).CompareTo(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(other));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_Contains_280d6f3d(
        long receiver,
        long span,
        out int result)
    {
        RoslynCallCounters.Record(1845);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Contains(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(span)) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_Contains_6dd56088(
        long receiver,
        int position,
        out int result)
    {
        RoslynCallCounters.Record(1846);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Contains(position) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_Equals_f0c3d453(
        long receiver,
        long other,
        out int result)
    {
        RoslynCallCounters.Record(1847);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Equals(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(other)) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_GetHashCode(
        long receiver,
        out int result)
    {
        RoslynCallCounters.Record(1849);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).GetHashCode();
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_Intersection(
        long receiver,
        long span,
        out long result)
    {
        RoslynCallCounters.Record(1850);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Intersection(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(span)) is { } value ? _owner.Objects.AddValue(value) : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_IntersectsWith_a6c6b98b(
        long receiver,
        long span,
        out int result)
    {
        RoslynCallCounters.Record(1851);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).IntersectsWith(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(span)) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_IntersectsWith_173790fd(
        long receiver,
        int position,
        out int result)
    {
        RoslynCallCounters.Record(1852);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).IntersectsWith(position) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_Overlap(
        long receiver,
        long span,
        out long result)
    {
        RoslynCallCounters.Record(1853);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Overlap(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(span)) is { } value ? _owner.Objects.AddValue(value) : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_OverlapsWith(
        long receiver,
        long span,
        out int result)
    {
        RoslynCallCounters.Record(1854);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).OverlapsWith(_owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(span)) ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public unsafe int TextSpan_ToString(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength)
    {
        RoslynCallCounters.Record(1855);
        requiredLength = default;

        try
        {
            if (bufferLength < 0) throw new global::System.ArgumentOutOfRangeException(nameof(bufferLength));
            string? __roslynAotValue = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).ToString();
            if (__roslynAotValue is null) { requiredLength = -1; return RoslynAbi.Success; }
            requiredLength = __roslynAotValue.Length;
            if (buffer == 0) return RoslynAbi.Success;
            if (bufferLength < requiredLength) throw new global::System.ArgumentException("The UTF-16 result buffer is too small.", nameof(bufferLength));
            __roslynAotValue.AsSpan().CopyTo(new global::System.Span<char>((void*)buffer, bufferLength));
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_get_End(
        long receiver,
        out int result)
    {
        RoslynCallCounters.Record(1856);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).End;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_get_IsEmpty(
        long receiver,
        out int result)
    {
        RoslynCallCounters.Record(1857);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).IsEmpty ? 1 : 0;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_get_Length(
        long receiver,
        out int result)
    {
        RoslynCallCounters.Record(1858);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Length;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }

    public int TextSpan_get_Start(
        long receiver,
        out int result)
    {
        RoslynCallCounters.Record(1859);
        result = default;

        try
        {
            result = _owner.Objects.GetValue<global::Microsoft.CodeAnalysis.Text.TextSpan>(receiver).Start;
            return RoslynAbi.Success;
        }
        catch (global::System.Exception exception)
        {
            return _owner.SetError(exception);
        }
    }
}
