<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <IsAotCompatible>true</IsAotCompatible>
    <AssemblyName>analyze-aot-sample-analyzer</AssemblyName>
    <_AnalyzerConfiguration>$([System.String]::Copy('$(Configuration)').ToLowerInvariant())</_AnalyzerConfiguration>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AnalyzeAot.AnalyzerRuntime/AnalyzeAot.AnalyzerRuntime.csproj" />
    <ProjectReference Include="../AnalyzeAot.SampleAnalyzer/AnalyzeAot.SampleAnalyzer.csproj"
                      ReferenceOutputAssembly="false" />
    <Reference Include="AnalyzeAot.SampleAnalyzer">
      <HintPath>../../artifacts/bin/AnalyzeAot.SampleAnalyzer/$(_AnalyzerConfiguration)/AnalyzeAot.SampleAnalyzer.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
