//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.Diagnostics
{
    public abstract partial class OperationBlockStartAnalysisContext
    {
        [System.Obsolete("Use CompilationWithAnalyzers instead. See https://github.com/dotnet/roslyn/issues/63440 for more details.")]
        protected OperationBlockStartAnalysisContext(System.Collections.Immutable.ImmutableArray<IOperation> operationBlocks, ISymbol owningSymbol, Compilation compilation, AnalyzerOptions options, System.Threading.CancellationToken cancellationToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public System.Threading.CancellationToken CancellationToken
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public Compilation Compilation
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public Text.TextSpan? FilterSpan
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.OperationBlockStartAnalysisContext_get_FilterSpan(__AnalyzeAotGetHandle(controlVtbl), out long result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : global::Microsoft.CodeAnalysis.Text.TextSpan.__AnalyzeAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxTree FilterTree
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public bool IsGeneratedCode
        {
            get
            {
                global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl = __AnalyzeAotGetControlVtbl();
                global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl vtbl = __AnalyzeAotGetVtbl();
                int status = vtbl.OperationBlockStartAnalysisContext_get_IsGeneratedCode(__AnalyzeAotGetHandle(controlVtbl), out int result);
                global::AnalyzeAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public System.Collections.Immutable.ImmutableArray<IOperation> OperationBlocks
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public AnalyzerOptions Options
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public ISymbol OwningSymbol
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        public FlowAnalysis.ControlFlowGraph GetControlFlowGraph(IOperation operationBlock)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        [System.Runtime.CompilerServices.OverloadResolutionPriority(-1)]
        public void RegisterOperationAction(System.Action<OperationAnalysisContext> action, params OperationKind[] operationKinds)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
        }

        public abstract void RegisterOperationAction(System.Action<OperationAnalysisContext> action, params System.Collections.Immutable.ImmutableArray<OperationKind> operationKinds);
        public abstract void RegisterOperationBlockEndAction(System.Action<OperationBlockAnalysisContext> action);
        internal OperationBlockStartAnalysisContext()
        {
        }

        private global::AnalyzeAot.Abi.IRoslynControlVtbl? __analyzeAotControlVtbl;
        private global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl? __analyzeAotVtbl;
        private long __analyzeAotHandle;
        internal OperationBlockStartAnalysisContext(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl vtbl, long handle)
        {
            __analyzeAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __analyzeAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __analyzeAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl __AnalyzeAotGetVtbl() => __analyzeAotVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        internal global::AnalyzeAot.Abi.IRoslynControlVtbl __AnalyzeAotGetControlVtbl() => __analyzeAotControlVtbl ?? throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        internal long __AnalyzeAotGetHandle(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl)
        {
            global::AnalyzeAot.Abi.IRoslynControlVtbl actual = __AnalyzeAotGetControlVtbl();
            if (!object.ReferenceEquals(actual, controlVtbl))
                throw new System.InvalidOperationException("Roslyn facade values cannot cross control vtbl identities.");
            return __analyzeAotHandle;
        }

        private sealed partial class __AnalyzeAotProxy : OperationBlockStartAnalysisContext
        {
            internal __AnalyzeAotProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, global::AnalyzeAot.Abi.IOperationBlockStartAnalysisContextVtbl vtbl, long handle) : base(controlVtbl, vtbl, handle)
            {
            }

            public override void RegisterOperationAction(System.Action<OperationAnalysisContext> action, params System.Collections.Immutable.ImmutableArray<OperationKind> operationKinds)
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }

            public override void RegisterOperationBlockEndAction(System.Action<OperationBlockAnalysisContext> action)
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by AnalyzeAot.");
            }
        }

        internal static OperationBlockStartAnalysisContext __AnalyzeAotCreateProxy(global::AnalyzeAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new __AnalyzeAotProxy(controlVtbl, global::AnalyzeAot.RoslynFacade.RoslynVtblFactory.GetOperationBlockStartAnalysisContextVtbl(controlVtbl), handle);
    }
}
