//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.FlowAnalysis
{
    public partial interface ControlFlowBranch
    {
        public BasicBlock? Destination
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_Destination(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : BasicBlock.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public System.Collections.Immutable.ImmutableArray<ControlFlowRegion> EnteringRegions
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_EnteringRegions(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return System.Collections.Immutable.ImmutableArray.CreateRange(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadObjectCollection<ControlFlowRegion>(controlVtbl, result, static (controlVtbl, handle) => ControlFlowRegion.__RoslynAotCreateProxy(controlVtbl, handle)));
            }
        }

        public System.Collections.Immutable.ImmutableArray<ControlFlowRegion> FinallyRegions
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_FinallyRegions(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return System.Collections.Immutable.ImmutableArray.CreateRange(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadObjectCollection<ControlFlowRegion>(controlVtbl, result, static (controlVtbl, handle) => ControlFlowRegion.__RoslynAotCreateProxy(controlVtbl, handle)));
            }
        }

        public bool IsConditionalSuccessor
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_IsConditionalSuccessor(__RoslynAotGetHandle(controlVtbl), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public System.Collections.Immutable.ImmutableArray<ControlFlowRegion> LeavingRegions
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_LeavingRegions(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return System.Collections.Immutable.ImmutableArray.CreateRange(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadObjectCollection<ControlFlowRegion>(controlVtbl, result, static (controlVtbl, handle) => ControlFlowRegion.__RoslynAotCreateProxy(controlVtbl, handle)));
            }
        }

        public ControlFlowBranchSemantics Semantics
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_Semantics(__RoslynAotGetHandle(controlVtbl), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return (ControlFlowBranchSemantics)result;
            }
        }

        public BasicBlock Source
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IControlFlowBranchVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ControlFlowBranch_get_Source(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return BasicBlock.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IControlFlowBranchVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetControlFlowBranchVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl) => __RoslynAotGetProxy().GetHandle(controlVtbl);
        internal static ControlFlowBranch __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (ControlFlowBranch)(object)new global::RoslynAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("97dfafe2-6369-5dd0-90a1-35657555841c")]
        internal partial interface __RoslynAotImplementation : ControlFlowBranch
        {
        }
    }
}
