<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <AssemblyName>Microsoft.CodeAnalysis.CSharp</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <PublicSign>true</PublicSign>
    <AssemblyOriginatorKeyFile>../../eng/Microsoft.CodeAnalysis.public.snk</AssemblyOriginatorKeyFile>
    <NoWarn>$(NoWarn);CS0108;CS0169;CS0659;CS8669;CA2256;RSEXPERIMENTAL006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RoslynAot.Abi/RoslynAot.Abi.csproj" />
    <ProjectReference Include="../RoslynAot.GeneratedFacade.Runtime/RoslynAot.GeneratedFacade.Runtime.csproj" />
    <ProjectReference Include="../RoslynAot.GeneratedFacade/RoslynAot.GeneratedFacade.csproj" />
    <Compile Include="../RoslynAot.Generated/Projection/Facades/Microsoft.CodeAnalysis.CSharp/**/*.cs"
             Link="Generated/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
