<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <AssemblyName>Microsoft.CodeAnalysis.CSharp.Test.Utilities</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <PublicSign>true</PublicSign>
    <AssemblyOriginatorKeyFile>../../eng/Roslyn.Test.public.snk</AssemblyOriginatorKeyFile>
    <NoWarn>$(NoWarn);RS1001;RS1025;RS1026</NoWarn>
    <_RoslynBincore>$(RoslynTargetsPath)/bincore</_RoslynBincore>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AnalyzeAot.Abi/AnalyzeAot.Abi.csproj" />
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>$(_RoslynBincore)/Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>$(_RoslynBincore)/Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyAnalyzeAotExecutable"
          AfterTargets="Publish"
          Condition="'$(PublishAot)' == 'true'">
    <Copy SourceFiles="$(PublishDir)$(AssemblyName)$(ExeExtension)"
          DestinationFiles="$(PublishDir)analyze-aot$(ExeExtension)" />
  </Target>

</Project>
