<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <IsAotCompatible>true</IsAotCompatible>
    <AssemblyName>analyze-aot-roslyn-projection-client</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <PublicSign>true</PublicSign>
    <AssemblyOriginatorKeyFile>../../eng/Microsoft.CodeAnalysis.public.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AnalyzeAot.Abi/AnalyzeAot.Abi.csproj" />
    <ProjectReference Include="../../src/AnalyzeAot.GeneratedFacade.Runtime/AnalyzeAot.GeneratedFacade.Runtime.csproj" />
    <ProjectReference Include="../../src/AnalyzeAot.GeneratedFacade/AnalyzeAot.GeneratedFacade.csproj" />
    <ProjectReference Include="../../src/AnalyzeAot.GeneratedFacade.CSharp/AnalyzeAot.GeneratedFacade.CSharp.csproj" />
  </ItemGroup>

</Project>
