//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis
{
    public partial interface ITypeSymbol : INamespaceOrTypeSymbol, ISymbol, System.IEquatable<ISymbol?>
    {
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> AllInterfaces
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_AllInterfaces(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return System.Collections.Immutable.ImmutableArray.CreateRange(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadObjectCollection<INamedTypeSymbol>(controlVtbl, result, static (controlVtbl, handle) => INamedTypeSymbol.__RoslynAotCreateProxy(controlVtbl, handle)));
            }
        }

        INamedTypeSymbol? BaseType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_BaseType(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : INamedTypeSymbol.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        [System.Obsolete("This API will be removed in the future. Use INamedTypeSymbol.ExtensionParameter instead.")]
        IParameterSymbol? ExtensionParameter
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Obsolete APIs are not projected into compiler dispatch.");
            }
        }

        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> Interfaces
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_Interfaces(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return System.Collections.Immutable.ImmutableArray.CreateRange(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadObjectCollection<INamedTypeSymbol>(controlVtbl, result, static (controlVtbl, handle) => INamedTypeSymbol.__RoslynAotCreateProxy(controlVtbl, handle)));
            }
        }

        bool IsAnonymousType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsAnonymousType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        [System.Obsolete("This API will be removed in the future. Use INamedTypeSymbol.IsExtension instead.")]
        bool IsExtension
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Obsolete APIs are not projected into compiler dispatch.");
            }
        }

        bool IsNativeIntegerType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsNativeIntegerType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsReadOnly
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsReadOnly(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsRecord
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsRecord(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsReferenceType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsReferenceType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsRefLikeType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsRefLikeType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsTupleType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsTupleType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsUnmanagedType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsUnmanagedType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsValueType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_IsValueType(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        NullableAnnotation NullableAnnotation
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_NullableAnnotation(__RoslynAotGetHandle(), out byte result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return (NullableAnnotation)result;
            }
        }

        ITypeSymbol OriginalDefinition
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_OriginalDefinition(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return __RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        SpecialType SpecialType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_SpecialType(__RoslynAotGetHandle(), out sbyte result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return (SpecialType)result;
            }
        }

        TypeKind TypeKind
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.ITypeSymbol_get_TypeKind(__RoslynAotGetHandle(), out byte result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return (TypeKind)result;
            }
        }

        ISymbol? FindImplementationForInterfaceMember(ISymbol interfaceMember)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.ITypeSymbol_FindImplementationForInterfaceMember(__RoslynAotGetHandle(), interfaceMember.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return result == 0 ? null : ISymbol.__RoslynAotCreateProxy(controlVtbl, result);
        }

        System.Collections.Immutable.ImmutableArray<SymbolDisplayPart> ToDisplayParts(NullableFlowState topLevelNullability, SymbolDisplayFormat? format = null)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Return type is unsupported: Generic substitutions are not supported.");
        }

        string ToDisplayString(NullableFlowState topLevelNullability, SymbolDisplayFormat? format = null)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
            long __roslynAotReceiver = __RoslynAotGetHandle();
            return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.ITypeSymbol_ToDisplayString(__roslynAotReceiver, (byte)topLevelNullability, format is null ? 0L : format.__RoslynAotGetHandle(), buffer, bufferLength, out requiredLength))!;
        }

        System.Collections.Immutable.ImmutableArray<SymbolDisplayPart> ToMinimalDisplayParts(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat? format = null)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Return type is unsupported: Generic substitutions are not supported.");
        }

        string ToMinimalDisplayString(SemanticModel semanticModel, NullableFlowState topLevelNullability, int position, SymbolDisplayFormat? format = null)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
            long __roslynAotReceiver = __RoslynAotGetHandle();
            return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.ITypeSymbol_ToMinimalDisplayString(__roslynAotReceiver, semanticModel.__RoslynAotGetHandle(), (byte)topLevelNullability, position, format is null ? 0L : format.__RoslynAotGetHandle(), buffer, bufferLength, out requiredLength))!;
        }

        ITypeSymbol WithNullableAnnotation(NullableAnnotation nullableAnnotation)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IITypeSymbolVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.ITypeSymbol_WithNullableAnnotation(__RoslynAotGetHandle(), (byte)nullableAnnotation, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IITypeSymbolVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetITypeSymbolVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static ITypeSymbol __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (ITypeSymbol)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("49d17cb5-779f-55d7-b15c-cfae258ea06b")]
        internal partial interface __RoslynAotImplementation : ITypeSymbol
        {
        }
    }
}
