//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis
{
    public readonly partial struct LineMapping : System.IEquatable<LineMapping>
    {
        private readonly int _dummyPrimitive;
        public LineMapping(Text.LinePositionSpan span, int? characterOffset, FileLinePositionSpan mappedSpan)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public int? CharacterOffset
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
            }
        }

        public bool IsHidden
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.LineMapping_get_IsHidden(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public FileLinePositionSpan MappedSpan
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.LineMapping_get_MappedSpan(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return FileLinePositionSpan.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public Text.LinePositionSpan Span
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.LineMapping_get_Span(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return Text.LinePositionSpan.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public readonly bool Equals(LineMapping other)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.LineMapping_Equals_894d29f3(__RoslynAotGetHandle(), other.__RoslynAotGetHandle(), out int result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return result != 0;
        }

        public override readonly bool Equals(object? obj)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public override readonly int GetHashCode()
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.LineMapping_GetHashCode(__RoslynAotGetHandle(), out int result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return result;
        }

        public static bool operator ==(LineMapping left, LineMapping right)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public static bool operator !=(LineMapping left, LineMapping right)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public override readonly string? ToString()
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ILineMappingVtbl vtbl = __RoslynAotGetVtbl();
            long __roslynAotReceiver = __RoslynAotGetHandle();
            return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.LineMapping_ToString(__roslynAotReceiver, buffer, bufferLength, out requiredLength));
        }

        private readonly global::RoslynAot.Abi.IRoslynControlVtbl? __roslynAotControlVtbl;
        private readonly global::RoslynAot.Abi.ILineMappingVtbl? __roslynAotVtbl;
        private readonly long __roslynAotHandle;
        internal LineMapping(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, global::RoslynAot.Abi.ILineMappingVtbl vtbl, long handle)
        {
            this = default;
            __roslynAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __roslynAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __roslynAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::RoslynAot.Abi.ILineMappingVtbl __RoslynAotGetVtbl()
        {
            if (__roslynAotVtbl is not null)
                return __roslynAotVtbl;
            if (__roslynAotHandle == 0)
                return global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetLineMappingVtbl(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl());
            throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        }

        internal global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl()
        {
            if (__roslynAotControlVtbl is not null)
                return __roslynAotControlVtbl;
            if (__roslynAotHandle == 0)
                return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl();
            throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        }

        internal long __RoslynAotGetHandle() => __roslynAotHandle;
        internal static LineMapping __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new LineMapping(controlVtbl, global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetLineMappingVtbl(controlVtbl), handle);
    }
}
