//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis
{
    public readonly partial struct SymbolDisplayPart
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public SymbolDisplayPart(SymbolDisplayPartKind kind, ISymbol? symbol, string text)
        {
            this = default;
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl();
            global::RoslynAot.Abi.ISymbolDisplayPartTypeVtbl vtbl = global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetSymbolDisplayPartTypeVtbl(controlVtbl);
            int status = vtbl.SymbolDisplayPart_ctor((int)kind, symbol is null ? 0L : symbol.__RoslynAotGetHandle(controlVtbl), text, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            __roslynAotControlVtbl = controlVtbl;
            __roslynAotVtbl = global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetSymbolDisplayPartVtbl(controlVtbl);
            __roslynAotHandle = result;
        }

        public SymbolDisplayPartKind Kind
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ISymbolDisplayPartVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.SymbolDisplayPart_get_Kind(__RoslynAotGetHandle(controlVtbl), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return (SymbolDisplayPartKind)result;
            }
        }

        public ISymbol? Symbol
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ISymbolDisplayPartVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.SymbolDisplayPart_get_Symbol(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : ISymbol.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public override readonly string ToString()
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ISymbolDisplayPartVtbl vtbl = __RoslynAotGetVtbl();
            long __roslynAotReceiver = __RoslynAotGetHandle(controlVtbl);
            return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ReadUtf16String(controlVtbl, (nint buffer, int bufferLength, out int requiredLength) => vtbl.SymbolDisplayPart_ToString(__roslynAotReceiver, buffer, bufferLength, out requiredLength))!;
        }

        private readonly global::RoslynAot.Abi.IRoslynControlVtbl? __roslynAotControlVtbl;
        private readonly global::RoslynAot.Abi.ISymbolDisplayPartVtbl? __roslynAotVtbl;
        private readonly long __roslynAotHandle;
        internal SymbolDisplayPart(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, global::RoslynAot.Abi.ISymbolDisplayPartVtbl vtbl, long handle)
        {
            this = default;
            __roslynAotControlVtbl = controlVtbl ?? throw new System.ArgumentNullException(nameof(controlVtbl));
            __roslynAotVtbl = vtbl ?? throw new System.ArgumentNullException(nameof(vtbl));
            __roslynAotHandle = handle != 0 ? handle : throw new System.ArgumentOutOfRangeException(nameof(handle));
        }

        internal global::RoslynAot.Abi.ISymbolDisplayPartVtbl __RoslynAotGetVtbl()
        {
            if (__roslynAotVtbl is not null)
                return __roslynAotVtbl;
            if (__roslynAotHandle == 0)
                return global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetSymbolDisplayPartVtbl(global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl());
            throw new System.InvalidOperationException("This Roslyn facade value has no vtbl.");
        }

        internal global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl()
        {
            if (__roslynAotControlVtbl is not null)
                return __roslynAotControlVtbl;
            if (__roslynAotHandle == 0)
                return global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.GetCurrentControlVtbl();
            throw new System.InvalidOperationException("This Roslyn facade value has no control vtbl.");
        }

        internal long __RoslynAotGetHandle(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl) => __roslynAotHandle;
        internal static SymbolDisplayPart __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => new SymbolDisplayPart(controlVtbl, global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetSymbolDisplayPartVtbl(controlVtbl), handle);
    }
}
