//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("d4b3cd8e-9a63-589e-9bb2-1984d78532db")]
public partial interface IAnalyzerImageReferenceVtbl : IAnalyzerReferenceVtbl
{

    [PreserveSig]
    int AnalyzerImageReference_get_Display(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int AnalyzerImageReference_get_FullPath(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );
}
