//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("43451624-2ce0-5776-8da0-8c4156b9cef7")]
public partial interface IAnonymousObjectCreationExpressionSyntaxVtbl : IExpressionSyntaxVtbl
{

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_Accept_198a2295(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_AddInitializers(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_WithCloseBraceToken(
        long receiver,
        long closeBraceToken,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_WithNewKeyword(
        long receiver,
        long newKeyword,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_WithOpenBraceToken(
        long receiver,
        long openBraceToken,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_get_CloseBraceToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_get_NewKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int AnonymousObjectCreationExpressionSyntax_get_OpenBraceToken(
        long receiver,
        out long result
    );
}
