//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("ec855c99-cdf1-5b5a-8d82-56e1c2d3d4ba")]
public partial interface IArrayRankSpecifierSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int ArrayRankSpecifierSyntax_Accept_34e32e14(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_AddSizes(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_WithCloseBracketToken(
        long receiver,
        long closeBracketToken,
        out long result
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_WithOpenBracketToken(
        long receiver,
        long openBracketToken,
        out long result
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_get_CloseBracketToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_get_OpenBracketToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ArrayRankSpecifierSyntax_get_Rank(
        long receiver,
        out int result
    );
}
