//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("7afee8e3-5840-5f98-a78e-f602d7721340")]
public partial interface IBranchingDirectiveTriviaSyntaxVtbl : IDirectiveTriviaSyntaxVtbl
{

    [PreserveSig]
    int BranchingDirectiveTriviaSyntax_WithEndOfDirectiveToken(
        long receiver,
        long endOfDirectiveToken,
        out long result
    );

    [PreserveSig]
    int BranchingDirectiveTriviaSyntax_WithHashToken(
        long receiver,
        long hashToken,
        out long result
    );

    [PreserveSig]
    int BranchingDirectiveTriviaSyntax_get_BranchTaken(
        long receiver,
        out int result
    );
}
