//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("94eb7e1f-6be9-5fea-92ac-94d53b0b81d9")]
public partial interface IControlFlowBranchVtbl
{

    [PreserveSig]
    int ControlFlowBranch_get_Destination(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ControlFlowBranch_get_EnteringRegions(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ControlFlowBranch_get_FinallyRegions(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ControlFlowBranch_get_IsConditionalSuccessor(
        long receiver,
        out int result
    );

    [PreserveSig]
    int ControlFlowBranch_get_LeavingRegions(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ControlFlowBranch_get_Semantics(
        long receiver,
        out int result
    );

    [PreserveSig]
    int ControlFlowBranch_get_Source(
        long receiver,
        out long result
    );
}
