//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("c8a52d6d-f833-52da-83a2-82207335d95a")]
public partial interface IConditionalDirectiveTriviaSyntaxVtbl : IBranchingDirectiveTriviaSyntaxVtbl
{

    [PreserveSig]
    int ConditionalDirectiveTriviaSyntax_WithCondition(
        long receiver,
        long condition,
        out long result
    );

    [PreserveSig]
    int ConditionalDirectiveTriviaSyntax_get_ConditionValue(
        long receiver,
        out int result
    );

    [PreserveSig]
    int ConditionalDirectiveTriviaSyntax_get_Condition(
        long receiver,
        out long result
    );
}
