//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("539599e1-6e83-56ce-9ba8-c13ec16e0fa2")]
public partial interface IConditionalAccessExpressionSyntaxVtbl : IExpressionSyntaxVtbl
{

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_Accept_5ff4358e(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_Update(
        long receiver,
        long expression,
        long operatorToken,
        long whenNotNull,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_WithExpression(
        long receiver,
        long expression,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_WithOperatorToken(
        long receiver,
        long operatorToken,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_WithWhenNotNull(
        long receiver,
        long whenNotNull,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_get_Expression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_get_OperatorToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ConditionalAccessExpressionSyntax_get_WhenNotNull(
        long receiver,
        out long result
    );
}
