//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("9f7f627c-d4f5-5090-8c28-316ab7ff2b2c")]
public partial interface ICrefBracketedParameterListSyntaxVtbl : IBaseCrefParameterListSyntaxVtbl
{

    [PreserveSig]
    int CrefBracketedParameterListSyntax_Accept_6ee4108a(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int CrefBracketedParameterListSyntax_WithCloseBracketToken(
        long receiver,
        long closeBracketToken,
        out long result
    );

    [PreserveSig]
    int CrefBracketedParameterListSyntax_WithOpenBracketToken(
        long receiver,
        long openBracketToken,
        out long result
    );

    [PreserveSig]
    int CrefBracketedParameterListSyntax_get_CloseBracketToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int CrefBracketedParameterListSyntax_get_OpenBracketToken(
        long receiver,
        out long result
    );
}
