//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("25f9b44e-fa1f-514d-a074-5f783f4e2515")]
public partial interface ICSharpCommandLineParserTypeVtbl
{

    [PreserveSig]
    int CSharpCommandLineParser_get_Default(
        out long result
    );

    [PreserveSig]
    int CSharpCommandLineParser_get_Script(
        out long result
    );
}
