//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("88bd9cde-c220-5e9c-ad2f-72df0926d1a6")]
public partial interface IDiagnosticDescriptorVtbl
{

    [PreserveSig]
    int DiagnosticDescriptor_Equals_7497f57f(
        long receiver,
        long other,
        out int result
    );

    [PreserveSig]
    int DiagnosticDescriptor_GetEffectiveSeverity(
        long receiver,
        long compilationOptions,
        out int result
    );

    [PreserveSig]
    int DiagnosticDescriptor_GetHashCode(
        long receiver,
        out int result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_Category(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_CustomTags(
        long receiver,
        out long result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_DefaultSeverity(
        long receiver,
        out int result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_Description(
        long receiver,
        out long result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_HelpLinkUri(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_Id(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_IsEnabledByDefault(
        long receiver,
        out int result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_MessageFormat(
        long receiver,
        out long result
    );

    [PreserveSig]
    int DiagnosticDescriptor_get_Title(
        long receiver,
        out long result
    );
}
