//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("048fbe22-e5c8-5604-9344-8d0f561dfbb6")]
public partial interface IExtensionMemberCrefSyntaxVtbl : IMemberCrefSyntaxVtbl
{

    [PreserveSig]
    int ExtensionMemberCrefSyntax_Accept_cdcaa02e(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_AddParametersParameters(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_AddTypeArgumentListArguments(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_Update(
        long receiver,
        long extensionKeyword,
        long typeArgumentList,
        long parameters,
        long dotToken,
        long member,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_WithDotToken(
        long receiver,
        long dotToken,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_WithExtensionKeyword(
        long receiver,
        long extensionKeyword,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_WithMember(
        long receiver,
        long member,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_WithParameters(
        long receiver,
        long parameters,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_WithTypeArgumentList(
        long receiver,
        long typeArgumentList,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_get_DotToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_get_ExtensionKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_get_Member(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_get_Parameters(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExtensionMemberCrefSyntax_get_TypeArgumentList(
        long receiver,
        out long result
    );
}
