//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("8ced7bf1-e533-58f5-82ba-8360abcdc2a1")]
public partial interface IGeneratorAttributeSyntaxContextVtbl
{

    [PreserveSig]
    int GeneratorAttributeSyntaxContext_get_Attributes(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GeneratorAttributeSyntaxContext_get_SemanticModel(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GeneratorAttributeSyntaxContext_get_TargetNode(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GeneratorAttributeSyntaxContext_get_TargetSymbol(
        long receiver,
        out long result
    );
}
