//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("126518b6-7638-5b3d-bdd0-c654711cf0f1")]
public partial interface IGroupClauseSyntaxVtbl : ISelectOrGroupClauseSyntaxVtbl
{

    [PreserveSig]
    int GroupClauseSyntax_Accept_dcccbb0a(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int GroupClauseSyntax_Update(
        long receiver,
        long groupKeyword,
        long groupExpression,
        long byKeyword,
        long byExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithByExpression(
        long receiver,
        long byExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithByKeyword(
        long receiver,
        long byKeyword,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithGroupExpression(
        long receiver,
        long groupExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithGroupKeyword(
        long receiver,
        long groupKeyword,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_ByExpression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_ByKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_GroupExpression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_GroupKeyword(
        long receiver,
        out long result
    );
}
