//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("a6c24267-e8d5-50b3-82e4-0fdb9e7235ad")]
public partial interface IGroupClauseSyntaxVtbl : ISelectOrGroupClauseSyntaxVtbl
{

    [PreserveSig]
    int GroupClauseSyntax_Accept_1b6d9b57(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int GroupClauseSyntax_Update(
        long receiver,
        long groupKeyword,
        long groupExpression,
        long byKeyword,
        long byExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithByExpression(
        long receiver,
        long byExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithByKeyword(
        long receiver,
        long byKeyword,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithGroupExpression(
        long receiver,
        long groupExpression,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_WithGroupKeyword(
        long receiver,
        long groupKeyword,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_ByExpression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_ByKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_GroupExpression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int GroupClauseSyntax_get_GroupKeyword(
        long receiver,
        out long result
    );
}
