//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("fc4a330a-5c4f-5191-b127-95b73fc72fd8")]
public partial interface IIAnalyzerAssemblyLoaderVtbl
{

    [PreserveSig]
    int IAnalyzerAssemblyLoader_AddDependencyLocation(
        long receiver,
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string fullPath
    );
}
