//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("59636647-99d0-5e6c-9e28-c8edb7c356b7")]
public partial interface IIBinaryOperationVtbl
{

    [PreserveSig]
    int IBinaryOperation_get_ConstrainedToType(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IBinaryOperation_get_IsChecked(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IBinaryOperation_get_IsCompareText(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IBinaryOperation_get_IsLifted(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IBinaryOperation_get_LeftOperand(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IBinaryOperation_get_OperatorKind(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IBinaryOperation_get_OperatorMethod(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IBinaryOperation_get_RightOperand(
        long receiver,
        out long result
    );
}
