//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("ba0c81f1-35b5-5147-911a-bc3fa5cc4ce7")]
public partial interface IIDeclarationPatternOperationVtbl
{

    [PreserveSig]
    int IDeclarationPatternOperation_get_DeclaredSymbol(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IDeclarationPatternOperation_get_MatchedType(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IDeclarationPatternOperation_get_MatchesNull(
        long receiver,
        out int result
    );
}
