//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("c809afc4-66f9-5a2d-a89e-017c0e3ab4d8")]
public partial interface IIDiscardSymbolVtbl
{

    [PreserveSig]
    int IDiscardSymbol_get_NullableAnnotation(
        long receiver,
        out byte result
    );

    [PreserveSig]
    int IDiscardSymbol_get_Type(
        long receiver,
        out long result
    );
}
