//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("b36e435a-54f9-5685-bf0f-17de452e83f2")]
public partial interface IIInstanceReferenceOperationVtbl
{

    [PreserveSig]
    int IInstanceReferenceOperation_get_ReferenceKind(
        long receiver,
        out int result
    );
}
