//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("3db1e184-837f-5d70-abb1-002e8b801f5a")]
public partial interface IINameOfOperationVtbl
{

    [PreserveSig]
    int INameOfOperation_get_Argument(
        long receiver,
        out long result
    );
}
