//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("6695c09d-84cd-52cd-8f6d-76bb915f2874")]
public partial interface IIOperationOperationListReversedVtbl
{

    [PreserveSig]
    int IOperation_OperationList_Reversed_GetEnumerator(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IOperation_OperationList_Reversed_ToImmutableArray(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IOperation_OperationList_Reversed_get_Count(
        long receiver,
        out int result
    );
}
