//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("f74131e2-2d2d-504c-8abb-307300e9ec25")]
public partial interface IIPatternCaseClauseOperationVtbl
{

    [PreserveSig]
    int IPatternCaseClauseOperation_get_Guard(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPatternCaseClauseOperation_get_Label(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPatternCaseClauseOperation_get_Pattern(
        long receiver,
        out long result
    );
}
