//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("9630497f-cbb7-5286-8708-1e3ab0d4e840")]
public partial interface IIPropertySymbolVtbl
{

    [PreserveSig]
    int IPropertySymbol_ReduceExtensionMember(
        long receiver,
        long receiverType,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_ExplicitInterfaceImplementations(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_GetMethod(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsIndexer(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsPartialDefinition(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsReadOnly(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsRequired(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsWithEvents(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_IsWriteOnly(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_NullableAnnotation(
        long receiver,
        out byte result
    );

    [PreserveSig]
    int IPropertySymbol_get_OriginalDefinition(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_OverriddenProperty(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_Parameters(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_PartialDefinitionPart(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_PartialImplementationPart(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_RefCustomModifiers(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_RefKind(
        long receiver,
        out byte result
    );

    [PreserveSig]
    int IPropertySymbol_get_ReturnsByRefReadonly(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_ReturnsByRef(
        long receiver,
        out int result
    );

    [PreserveSig]
    int IPropertySymbol_get_SetMethod(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_TypeCustomModifiers(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IPropertySymbol_get_Type(
        long receiver,
        out long result
    );
}
