//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("eb113d5d-e961-538a-a0ac-9313b58322bf")]
public partial interface IIVariableDeclarationOperationVtbl
{

    [PreserveSig]
    int IVariableDeclarationOperation_get_Declarators(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IVariableDeclarationOperation_get_IgnoredDimensions(
        long receiver,
        out long result
    );

    [PreserveSig]
    int IVariableDeclarationOperation_get_Initializer(
        long receiver,
        out long result
    );
}
