//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("e52fbd58-1cf6-53f7-88a5-7c20ac69c946")]
public partial interface IModuleMetadataTypeVtbl
{

    [PreserveSig]
    int ModuleMetadata_CreateFromFile(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string path,
        out long result
    );
}
