//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("c85989a6-52da-5dc8-8c34-a04ba40efab3")]
public partial interface IModelExtensionsVtbl
{

    [PreserveSig]
    int ModelExtensions_AnalyzeControlFlow_e3b1d041(
        long semanticModel,
        long statement,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_AnalyzeControlFlow_79ec334b(
        long semanticModel,
        long firstStatement,
        long lastStatement,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_AnalyzeDataFlow_3f9d2c2d(
        long semanticModel,
        long statementOrExpression,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_AnalyzeDataFlow_2356859c(
        long semanticModel,
        long firstStatement,
        long lastStatement,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetAliasInfo(
        long semanticModel,
        long nameSyntax,
        long cancellationToken,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetDeclaredSymbol(
        long semanticModel,
        long declaration,
        long cancellationToken,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetMemberGroup(
        long semanticModel,
        long node,
        long cancellationToken,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetSpeculativeAliasInfo(
        long semanticModel,
        int position,
        long nameSyntax,
        int bindingOption,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetSpeculativeSymbolInfo(
        long semanticModel,
        int position,
        long expression,
        int bindingOption,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetSpeculativeTypeInfo(
        long semanticModel,
        int position,
        long expression,
        int bindingOption,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetSymbolInfo(
        long semanticModel,
        long node,
        long cancellationToken,
        out long result
    );

    [PreserveSig]
    int ModelExtensions_GetTypeInfo(
        long semanticModel,
        long node,
        long cancellationToken,
        out long result
    );
}
