//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("2ca287ce-f2a5-556a-8b39-cd78df1172cc")]
public partial interface IOperationBlockStartAnalysisContextVtbl
{

    [PreserveSig]
    int OperationBlockStartAnalysisContext_GetControlFlowGraph(
        long receiver,
        long operationBlock,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_Compilation(
        long receiver,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_FilterSpan(
        long receiver,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_FilterTree(
        long receiver,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_IsGeneratedCode(
        long receiver,
        out int result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_OperationBlocks(
        long receiver,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_Options(
        long receiver,
        out long result
    );

    [PreserveSig]
    int OperationBlockStartAnalysisContext_get_OwningSymbol(
        long receiver,
        out long result
    );
}
