//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("e20e1fa2-1d72-5e7f-af7b-8ada0a2cd40b")]
public partial interface IParenthesizedExpressionSyntaxVtbl : IExpressionSyntaxVtbl
{

    [PreserveSig]
    int ParenthesizedExpressionSyntax_Accept_ed86ec10(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_Update(
        long receiver,
        long openParenToken,
        long expression,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_WithCloseParenToken(
        long receiver,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_WithExpression(
        long receiver,
        long expression,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_WithOpenParenToken(
        long receiver,
        long openParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_get_CloseParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_get_Expression(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ParenthesizedExpressionSyntax_get_OpenParenToken(
        long receiver,
        out long result
    );
}
