//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("2e479d9e-b89e-5ebb-a4fb-5525ea752460")]
public partial interface IParenthesizedPatternSyntaxVtbl : IPatternSyntaxVtbl
{

    [PreserveSig]
    int ParenthesizedPatternSyntax_Accept_faea63e1(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_Update(
        long receiver,
        long openParenToken,
        long pattern,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_WithCloseParenToken(
        long receiver,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_WithOpenParenToken(
        long receiver,
        long openParenToken,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_WithPattern(
        long receiver,
        long pattern,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_get_CloseParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_get_OpenParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ParenthesizedPatternSyntax_get_Pattern(
        long receiver,
        out long result
    );
}
