//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("dfbce5d5-eace-5f0f-b6e9-392bc2239931")]
public partial interface IRuleSetIncludeVtbl
{

    [PreserveSig]
    int RuleSetInclude_LoadRuleSet(
        long receiver,
        long parent,
        out long result
    );

    [PreserveSig]
    int RuleSetInclude_get_Action(
        long receiver,
        out int result
    );

    [PreserveSig]
    int RuleSetInclude_get_IncludePath(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );
}
