//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("9b30029b-348d-5640-86f1-06cf49b47a9b")]
public partial interface ISemanticModelAnalysisContextVtbl
{

    [PreserveSig]
    int SemanticModelAnalysisContext_ReportDiagnostic(
        long receiver,
        long diagnostic
    );

    [PreserveSig]
    int SemanticModelAnalysisContext_get_FilterSpan(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SemanticModelAnalysisContext_get_FilterTree(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SemanticModelAnalysisContext_get_IsGeneratedCode(
        long receiver,
        out int result
    );

    [PreserveSig]
    int SemanticModelAnalysisContext_get_Options(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SemanticModelAnalysisContext_get_SemanticModel(
        long receiver,
        out long result
    );
}
