//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("3197eb40-df3c-5e64-9624-a17367cd4adc")]
public partial interface IShebangDirectiveTriviaSyntaxVtbl : IDirectiveTriviaSyntaxVtbl
{

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_Accept_3cddf934(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_Update(
        long receiver,
        long hashToken,
        long exclamationToken,
        long endOfDirectiveToken,
        int isActive,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_WithContent(
        long receiver,
        long content,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_WithEndOfDirectiveToken(
        long receiver,
        long endOfDirectiveToken,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_WithExclamationToken(
        long receiver,
        long exclamationToken,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_WithHashToken(
        long receiver,
        long hashToken,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_WithIsActive(
        long receiver,
        int isActive,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_get_Content(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_get_EndOfDirectiveToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_get_ExclamationToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_get_HashToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ShebangDirectiveTriviaSyntax_get_IsActive(
        long receiver,
        out int result
    );
}
