//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("ff83aa5d-a2e9-5ca7-b253-f892624d4664")]
public partial interface ISimpleNameSyntaxVtbl : INameSyntaxVtbl
{

    [PreserveSig]
    int SimpleNameSyntax_WithIdentifier(
        long receiver,
        long identifier,
        out long result
    );

    [PreserveSig]
    int SimpleNameSyntax_get_Identifier(
        long receiver,
        out long result
    );
}
