//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("eec051b8-fbeb-567a-bc48-a49327e21ab1")]
public partial interface ISimpleBaseTypeSyntaxVtbl : IBaseTypeSyntaxVtbl
{

    [PreserveSig]
    int SimpleBaseTypeSyntax_Accept_b6fe3437(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int SimpleBaseTypeSyntax_Update(
        long receiver,
        long @type,
        out long result
    );

    [PreserveSig]
    int SimpleBaseTypeSyntax_WithType(
        long receiver,
        long @type,
        out long result
    );

    [PreserveSig]
    int SimpleBaseTypeSyntax_get_Type(
        long receiver,
        out long result
    );
}
