//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("f4de1345-a737-52ae-ba5a-5f36d0491989")]
public partial interface ISizeOfExpressionSyntaxVtbl : IExpressionSyntaxVtbl
{

    [PreserveSig]
    int SizeOfExpressionSyntax_Accept_277b34c1(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_Update(
        long receiver,
        long keyword,
        long openParenToken,
        long @type,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_WithCloseParenToken(
        long receiver,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_WithKeyword(
        long receiver,
        long keyword,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_WithOpenParenToken(
        long receiver,
        long openParenToken,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_WithType(
        long receiver,
        long @type,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_get_CloseParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_get_Keyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_get_OpenParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SizeOfExpressionSyntax_get_Type(
        long receiver,
        out long result
    );
}
