//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("292cc399-ea7d-56ef-9baf-34d411ede39e")]
public partial interface ISlicePatternSyntaxVtbl : IPatternSyntaxVtbl
{

    [PreserveSig]
    int SlicePatternSyntax_Accept_581e5bfc(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int SlicePatternSyntax_Update(
        long receiver,
        long dotDotToken,
        long pattern,
        out long result
    );

    [PreserveSig]
    int SlicePatternSyntax_WithDotDotToken(
        long receiver,
        long dotDotToken,
        out long result
    );

    [PreserveSig]
    int SlicePatternSyntax_WithPattern(
        long receiver,
        long pattern,
        out long result
    );

    [PreserveSig]
    int SlicePatternSyntax_get_DotDotToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SlicePatternSyntax_get_Pattern(
        long receiver,
        out long result
    );
}
