//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("6008a4e4-5e86-5809-8ed8-ac71513415cf")]
public partial interface ISwitchSectionSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int SwitchSectionSyntax_Accept_63c2836f(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int SwitchSectionSyntax_AddLabels(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int SwitchSectionSyntax_AddStatements(
        long receiver,
        long items,
        out long result
    );
}
