//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("f0000a5c-8cb5-5017-a94d-9e9191b02f18")]
public partial interface ISwitchSectionSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int SwitchSectionSyntax_Accept_f172f8d3(
        long receiver,
        long visitor
    );
}
