//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("7ffc46df-576d-520c-9859-a3edf2dff24a")]
public partial interface ISyntaxTriviaListReversedTypeVtbl
{

    [PreserveSig]
    int SyntaxTriviaList_Reversed_ctor(
        long list,
        out long result
    );
}
