//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("20793b3c-f483-5711-8891-a9687e409530")]
public partial interface ISyntaxNodeOrTokenListVtbl
{

    [PreserveSig]
    int SyntaxNodeOrTokenList_Add(
        long receiver,
        long nodeOrToken,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Any(
        long receiver,
        out int result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Equals_c417d796(
        long receiver,
        long other,
        out int result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_FirstOrDefault(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_First(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_GetEnumerator(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_GetHashCode(
        long receiver,
        out int result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_IndexOf(
        long receiver,
        long nodeOrToken,
        out int result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Insert(
        long receiver,
        int index,
        long nodeOrToken,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_LastOrDefault(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Last(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_RemoveAt(
        long receiver,
        int index,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Remove(
        long receiver,
        long nodeOrTokenInList,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_Replace(
        long receiver,
        long nodeOrTokenInList,
        long newNodeOrToken,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_ToFullString(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_ToString(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_get_Count(
        long receiver,
        out int result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_get_FullSpan(
        long receiver,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_get_this__(
        long receiver,
        int index,
        out long result
    );

    [PreserveSig]
    int SyntaxNodeOrTokenList_get_Span(
        long receiver,
        out long result
    );
}
