//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("f87e6c44-2293-5d96-a5d4-2839265a18c7")]
public partial interface ISyntaxAnnotationTypeVtbl
{

    [PreserveSig]
    int SyntaxAnnotation_ctor_706a5ffb(
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_ctor_6d2856e8(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string kind,
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_ctor_ca78ae06(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string kind,
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string data,
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_get_ElasticAnnotation(
        out long result
    );
}
