//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("f2d45b79-f71f-5b15-a197-9ffb86684130")]
public partial interface ISyntaxAnnotationTypeVtbl
{

    [PreserveSig]
    int SyntaxAnnotation_ctor_3d9c3533(
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_ctor_0d8b8281(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string kind,
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_ctor_649fee3b(
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string kind,
        [global::System.Runtime.InteropServices.Marshalling.MarshalUsing(typeof(global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller))] string data,
        out long result
    );

    [PreserveSig]
    int SyntaxAnnotation_get_ElasticAnnotation(
        out long result
    );
}
