//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("b867566c-6a07-5fca-af9c-3115024f7a80")]
public partial interface ISyntaxTriviaListTypeVtbl
{

    [PreserveSig]
    int SyntaxTriviaList_ctor_d4e3748a(
        long trivia,
        out long result
    );

    [PreserveSig]
    int SyntaxTriviaList_Create_bcf3c646(
        long trivia,
        out long result
    );

    [PreserveSig]
    int SyntaxTriviaList_get_Empty(
        out long result
    );
}
