//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("deb1a0a6-3276-5eea-b017-9293e9e2ce48")]
public partial interface ITupleExpressionSyntaxVtbl : IExpressionSyntaxVtbl
{

    [PreserveSig]
    int TupleExpressionSyntax_Accept_6cddbd4a(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int TupleExpressionSyntax_AddArguments(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TupleExpressionSyntax_WithCloseParenToken(
        long receiver,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int TupleExpressionSyntax_WithOpenParenToken(
        long receiver,
        long openParenToken,
        out long result
    );

    [PreserveSig]
    int TupleExpressionSyntax_get_CloseParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int TupleExpressionSyntax_get_OpenParenToken(
        long receiver,
        out long result
    );
}
