//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("b32ccadb-448c-5b46-96c3-57096c6de5d2")]
public partial interface ITypeDeclarationSyntaxVtbl : IBaseTypeDeclarationSyntaxVtbl
{

    [PreserveSig]
    int TypeDeclarationSyntax_AddAttributeLists(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_AddBaseListTypes(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_AddConstraintClauses(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_AddMembers(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_AddParameterListParameters(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_AddTypeParameterListParameters(
        long receiver,
        long items,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithBaseList(
        long receiver,
        long baseList,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithCloseBraceToken(
        long receiver,
        long closeBraceToken,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithIdentifier(
        long receiver,
        long identifier,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithKeyword(
        long receiver,
        long keyword,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithModifiers(
        long receiver,
        long modifiers,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithOpenBraceToken(
        long receiver,
        long openBraceToken,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithParameterList(
        long receiver,
        long parameterList,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithSemicolonToken(
        long receiver,
        long semicolonToken,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_WithTypeParameterList(
        long receiver,
        long typeParameterList,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_get_Arity(
        long receiver,
        out int result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_get_Keyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_get_ParameterList(
        long receiver,
        out long result
    );

    [PreserveSig]
    int TypeDeclarationSyntax_get_TypeParameterList(
        long receiver,
        out long result
    );
}
