//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

[GeneratedComInterface]
[Guid("a726274e-d8b7-54fe-8dc6-f56fea9c2d5a")]
public partial interface ITypeCrefSyntaxVtbl : ICrefSyntaxVtbl
{

    [PreserveSig]
    int TypeCrefSyntax_Accept_8f9f03db(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int TypeCrefSyntax_Update(
        long receiver,
        long @type,
        out long result
    );

    [PreserveSig]
    int TypeCrefSyntax_WithType(
        long receiver,
        long @type,
        out long result
    );

    [PreserveSig]
    int TypeCrefSyntax_get_Type(
        long receiver,
        out long result
    );
}
