//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace RoslynAot.Abi;

public static unsafe class RoslynAbi
{
    public const int Success = 0;
    public const int InvalidArgument = unchecked((int)0x80070057);
    public const int ObjectDisposed = unchecked((int)0x80131622);
    public const int Unsupported = unchecked((int)0x80131515);
    public const int Failure = unchecked((int)0x80004005);

    public const string ManifestIdentity = "7a2b9089a7c19d9b942ce58b3cd53c71df21b95aa7a2f94625a7492f4a9c4d39";
    public const long ManifestIdentityLow = -7233412501175522438L;
    public const long ManifestIdentityHigh = 8159631080910302356L;

    public static uint Release(nint instance)
    {
        if (instance == 0)
        {
            return 0;
        }

        nint* vtable = *(nint**)instance;
        var release = (delegate* unmanaged<nint, uint>)vtable[2];
        return release(instance);
    }
}

public enum RoslynRemoteErrorKind
{
    None,
    Argument,
    ObjectDisposed,
    Unsupported,
    OperationCanceled,
    Failure,
}

public enum RoslynWellKnownObject
{
    SymbolEqualityComparerDefault,
    SymbolEqualityComparerIncludeNullability,
}

[GeneratedComInterface]
[Guid("7d26e69e-8fd6-55e3-8372-ddb51dd51bcf")]
public partial interface IRoslynControlVtbl
{
    [PreserveSig]
    int GetManifestIdentity(
        out long identityLow,
        out long identityHigh);

    [PreserveSig]
    int GetVtbl(
        long vtblIdLow,
        long vtblIdHigh,
        out nint vtbl);

    [PreserveSig]
    int CopyLastErrorUtf16(
        nint buffer,
        int bufferLength,
        out int requiredLength,
        out RoslynRemoteErrorKind errorKind);

    [PreserveSig]
    int CreateSourceTextUtf16(
        nint utf16Text,
        int utf16Length,
        int checksumAlgorithm,
        out long result);

    [PreserveSig]
    int IsObjectType(
        long handle,
        long vtblIdLow,
        long vtblIdHigh,
        out int isType);

    [PreserveSig]
    int CreateObjectCollection(
        nint handles,
        int count,
        out long result);

    [PreserveSig]
    int GetCollectionCount(
        long handle,
        out int count);

    [PreserveSig]
    int GetObjectCollectionItem(
        long handle,
        int index,
        out long result);

    [PreserveSig]
    int CopyStringCollectionItemUtf16(
        long handle,
        int index,
        nint buffer,
        int bufferLength,
        out int requiredLength);

    [PreserveSig]
    int GetWellKnownObject(
        RoslynWellKnownObject kind,
        out long result);

    [PreserveSig]
    int SymbolEqualityComparerEquals(
        RoslynWellKnownObject kind,
        long x,
        long y,
        out int result);

    [PreserveSig]
    int SymbolEqualityComparerGetHashCode(
        RoslynWellKnownObject kind,
        long symbol,
        out int result);

    [PreserveSig]
    int CopyObjectToStringUtf16(
        long handle,
        nint buffer,
        int bufferLength,
        out int requiredLength);

    [PreserveSig]
    int ObjectEquals(
        long handle,
        long other,
        out int result);

    [PreserveSig]
    int ObjectGetHashCode(
        long handle,
        out int result);
}
