//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.Operations
{
    public partial interface IIncrementOrDecrementOperation : IOperation
    {
        ITypeSymbol? ConstrainedToType
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_ConstrainedToType(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : ITypeSymbol.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        bool IsChecked
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_IsChecked(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsLifted
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_IsLifted(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        bool IsPostfix
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_IsPostfix(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        IMethodSymbol? OperatorMethod
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_OperatorMethod(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : IMethodSymbol.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        IOperation Target
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IIncrementOrDecrementOperation_get_Target(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return IOperation.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IIIncrementOrDecrementOperationVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetIIncrementOrDecrementOperationVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static IIncrementOrDecrementOperation __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (IIncrementOrDecrementOperation)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("b8de1c89-2794-5c76-8243-7ff6b52d18bc")]
        internal partial interface __RoslynAotImplementation : IIncrementOrDecrementOperation
        {
        }
    }
}
