//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface FinallyClauseSyntax : CSharpSyntaxNode
    {
        public BlockSyntax Block
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.FinallyClauseSyntax_get_Block(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return BlockSyntax.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken FinallyKeyword
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.FinallyClauseSyntax_get_FinallyKeyword(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_Accept_c563ca04(__RoslynAotGetHandle(controlVtbl), visitor.__RoslynAotGetHandle(controlVtbl));
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public sealed TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public FinallyClauseSyntax AddBlockAttributeLists(params AttributeListSyntax[] items)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_AddBlockAttributeLists(__RoslynAotGetHandle(controlVtbl), global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.CreateObjectCollectionHandle(controlVtbl, System.Array.ConvertAll(items, item => item.__RoslynAotGetHandle(controlVtbl))), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public FinallyClauseSyntax AddBlockStatements(params StatementSyntax[] items)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_AddBlockStatements(__RoslynAotGetHandle(controlVtbl), global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.CreateObjectCollectionHandle(controlVtbl, System.Array.ConvertAll(items, item => item.__RoslynAotGetHandle(controlVtbl))), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public FinallyClauseSyntax Update(SyntaxToken finallyKeyword, BlockSyntax block)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_Update(__RoslynAotGetHandle(controlVtbl), finallyKeyword.__RoslynAotGetHandle(controlVtbl), block.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public FinallyClauseSyntax WithBlock(BlockSyntax block)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_WithBlock(__RoslynAotGetHandle(controlVtbl), block.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public FinallyClauseSyntax WithFinallyKeyword(SyntaxToken finallyKeyword)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.FinallyClauseSyntax_WithFinallyKeyword(__RoslynAotGetHandle(controlVtbl), finallyKeyword.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IFinallyClauseSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetFinallyClauseSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl) => __RoslynAotGetProxy().GetHandle(controlVtbl);
        internal static FinallyClauseSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (FinallyClauseSyntax)(object)new global::RoslynAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("c5fe607b-b776-519e-bfed-e41b5364a46d")]
        internal partial interface __RoslynAotImplementation : FinallyClauseSyntax
        {
        }
    }
}
