//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface GotoStatementSyntax : StatementSyntax
    {
        public SyntaxList<AttributeListSyntax> AttributeLists
        {
            get
            {
                throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
            }
        }

        public SyntaxToken CaseOrDefaultKeyword
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.GotoStatementSyntax_get_CaseOrDefaultKeyword(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public ExpressionSyntax? Expression
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.GotoStatementSyntax_get_Expression(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result == 0 ? null : ExpressionSyntax.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken GotoKeyword
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.GotoStatementSyntax_get_GotoKeyword(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken SemicolonToken
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.GotoStatementSyntax_get_SemicolonToken(__RoslynAotGetHandle(controlVtbl), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_Accept_8e3f65fb(__RoslynAotGetHandle(controlVtbl), visitor.__RoslynAotGetHandle(controlVtbl));
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public sealed TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public new GotoStatementSyntax AddAttributeLists(params AttributeListSyntax[] items)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_AddAttributeLists(__RoslynAotGetHandle(controlVtbl), global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.CreateObjectCollectionHandle(controlVtbl, System.Array.ConvertAll(items, item => item.__RoslynAotGetHandle(controlVtbl))), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public GotoStatementSyntax Update(SyntaxList<AttributeListSyntax> attributeLists, SyntaxToken gotoKeyword, SyntaxToken caseOrDefaultKeyword, ExpressionSyntax? expression, SyntaxToken semicolonToken)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public GotoStatementSyntax Update(SyntaxToken gotoKeyword, SyntaxToken caseOrDefaultKeyword, ExpressionSyntax expression, SyntaxToken semicolonToken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_Update_2ddd503b(__RoslynAotGetHandle(controlVtbl), gotoKeyword.__RoslynAotGetHandle(controlVtbl), caseOrDefaultKeyword.__RoslynAotGetHandle(controlVtbl), expression.__RoslynAotGetHandle(controlVtbl), semicolonToken.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public new GotoStatementSyntax WithAttributeLists(SyntaxList<AttributeListSyntax> attributeLists)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot.");
        }

        public GotoStatementSyntax WithCaseOrDefaultKeyword(SyntaxToken caseOrDefaultKeyword)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_WithCaseOrDefaultKeyword(__RoslynAotGetHandle(controlVtbl), caseOrDefaultKeyword.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public GotoStatementSyntax WithExpression(ExpressionSyntax? expression)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_WithExpression(__RoslynAotGetHandle(controlVtbl), expression is null ? 0L : expression.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public GotoStatementSyntax WithGotoKeyword(SyntaxToken gotoKeyword)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_WithGotoKeyword(__RoslynAotGetHandle(controlVtbl), gotoKeyword.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public GotoStatementSyntax WithSemicolonToken(SyntaxToken semicolonToken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IGotoStatementSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.GotoStatementSyntax_WithSemicolonToken(__RoslynAotGetHandle(controlVtbl), semicolonToken.__RoslynAotGetHandle(controlVtbl), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IGotoStatementSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetGotoStatementSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl) => __RoslynAotGetProxy().GetHandle(controlVtbl);
        internal static GotoStatementSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (GotoStatementSyntax)(object)new global::RoslynAot.RoslynFacade.RoslynObjectProxy(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("bf790b74-3ae0-5bb3-80d8-21f6b7f089ca")]
        internal partial interface __RoslynAotImplementation : GotoStatementSyntax
        {
        }
    }
}
