//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface IfDirectiveTriviaSyntax : ConditionalDirectiveTriviaSyntax
    {
        public bool BranchTaken
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_BranchTaken(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public ExpressionSyntax Condition
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_Condition(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return ExpressionSyntax.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public bool ConditionValue
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_ConditionValue(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public SyntaxToken EndOfDirectiveToken
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_EndOfDirectiveToken(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken HashToken
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_HashToken(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken IfKeyword
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_IfKeyword(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public bool IsActive
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.IfDirectiveTriviaSyntax_get_IsActive(__RoslynAotGetHandle(), out int result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return result != 0;
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_Accept_284428f1(__RoslynAotGetHandle(), visitor.__RoslynAotGetHandle());
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public sealed TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Generic methods are not supported.");
        }

        public IfDirectiveTriviaSyntax Update(SyntaxToken hashToken, SyntaxToken ifKeyword, ExpressionSyntax condition, SyntaxToken endOfDirectiveToken, bool isActive, bool branchTaken, bool conditionValue)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_Update(__RoslynAotGetHandle(), hashToken.__RoslynAotGetHandle(), ifKeyword.__RoslynAotGetHandle(), condition.__RoslynAotGetHandle(), endOfDirectiveToken.__RoslynAotGetHandle(), isActive ? 1 : 0, branchTaken ? 1 : 0, conditionValue ? 1 : 0, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithBranchTaken(bool branchTaken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithBranchTaken(__RoslynAotGetHandle(), branchTaken ? 1 : 0, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public new IfDirectiveTriviaSyntax WithCondition(ExpressionSyntax condition)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithCondition(__RoslynAotGetHandle(), condition.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithConditionValue(bool conditionValue)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithConditionValue(__RoslynAotGetHandle(), conditionValue ? 1 : 0, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithEndOfDirectiveToken(SyntaxToken endOfDirectiveToken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithEndOfDirectiveToken(__RoslynAotGetHandle(), endOfDirectiveToken.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithHashToken(SyntaxToken hashToken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithHashToken(__RoslynAotGetHandle(), hashToken.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithIfKeyword(SyntaxToken ifKeyword)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithIfKeyword(__RoslynAotGetHandle(), ifKeyword.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public IfDirectiveTriviaSyntax WithIsActive(bool isActive)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.IfDirectiveTriviaSyntax_WithIsActive(__RoslynAotGetHandle(), isActive ? 1 : 0, out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IIfDirectiveTriviaSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetIfDirectiveTriviaSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static IfDirectiveTriviaSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (IfDirectiveTriviaSyntax)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("4b3dd411-0041-5418-bc76-4f013616129b")]
        internal partial interface __RoslynAotImplementation : IfDirectiveTriviaSyntax
        {
        }
    }
}
