//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface QueryExpressionSyntax : ExpressionSyntax
    {
        public QueryBodySyntax Body
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.QueryExpressionSyntax_get_Body(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return QueryBodySyntax.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public FromClauseSyntax FromClause
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.QueryExpressionSyntax_get_FromClause(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return FromClauseSyntax.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public void Accept(CSharpSyntaxVisitor visitor)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.QueryExpressionSyntax_Accept_c0695e6f(__RoslynAotGetHandle(), visitor.__RoslynAotGetHandle());
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
        }

        public sealed TResult? Accept<TResult>(CSharpSyntaxVisitor<TResult> visitor)
        {
            throw new System.PlatformNotSupportedException("This Roslyn API is not implemented by RoslynAot. Generic methods are not supported.");
        }

        public QueryExpressionSyntax AddBodyClauses(params QueryClauseSyntax[] items)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.QueryExpressionSyntax_AddBodyClauses(__RoslynAotGetHandle(), global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.CreateObjectCollectionHandle(controlVtbl, System.Array.ConvertAll(items, item => item.__RoslynAotGetHandle())), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public QueryExpressionSyntax Update(FromClauseSyntax fromClause, QueryBodySyntax body)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.QueryExpressionSyntax_Update(__RoslynAotGetHandle(), fromClause.__RoslynAotGetHandle(), body.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public QueryExpressionSyntax WithBody(QueryBodySyntax body)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.QueryExpressionSyntax_WithBody(__RoslynAotGetHandle(), body.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public QueryExpressionSyntax WithFromClause(FromClauseSyntax fromClause)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.QueryExpressionSyntax_WithFromClause(__RoslynAotGetHandle(), fromClause.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IQueryExpressionSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetQueryExpressionSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static QueryExpressionSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (QueryExpressionSyntax)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("cbd3f3d3-1897-5892-85bd-5df6e451d2b4")]
        internal partial interface __RoslynAotImplementation : QueryExpressionSyntax
        {
        }
    }
}
