//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface StructuredTriviaSyntax : CSharpSyntaxNode, IStructuredTriviaSyntax
    {
        public SyntaxTrivia ParentTrivia
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.IStructuredTriviaSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.StructuredTriviaSyntax_get_ParentTrivia(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxTrivia.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.IStructuredTriviaSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetStructuredTriviaSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static StructuredTriviaSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (StructuredTriviaSyntax)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("78f88ea0-a4d4-515d-bfb0-a11f3332ba95")]
        internal partial interface __RoslynAotImplementation : StructuredTriviaSyntax
        {
        }
    }
}
