//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.CodeAnalysis.CSharp.Syntax
{
    public partial interface SwitchLabelSyntax : CSharpSyntaxNode
    {
        public SyntaxToken ColonToken
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ISwitchLabelSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.SwitchLabelSyntax_get_ColonToken(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SyntaxToken Keyword
        {
            get
            {
                global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
                global::RoslynAot.Abi.ISwitchLabelSyntaxVtbl vtbl = __RoslynAotGetVtbl();
                int status = vtbl.SwitchLabelSyntax_get_Keyword(__RoslynAotGetHandle(), out long result);
                global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
                return SyntaxToken.__RoslynAotCreateProxy(controlVtbl, result);
            }
        }

        public SwitchLabelSyntax WithColonToken(SyntaxToken colonToken)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ISwitchLabelSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.SwitchLabelSyntax_WithColonToken(__RoslynAotGetHandle(), colonToken.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        public SwitchLabelSyntax WithKeyword(SyntaxToken keyword)
        {
            global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl = __RoslynAotGetControlVtbl();
            global::RoslynAot.Abi.ISwitchLabelSyntaxVtbl vtbl = __RoslynAotGetVtbl();
            int status = vtbl.SwitchLabelSyntax_WithKeyword(__RoslynAotGetHandle(), keyword.__RoslynAotGetHandle(), out long result);
            global::RoslynAot.RoslynFacade.RoslynFacadeRuntime.ThrowIfFailed(controlVtbl, status);
            return __RoslynAotCreateProxy(controlVtbl, result);
        }

        private global::RoslynAot.RoslynFacade.RoslynObjectProxy __RoslynAotGetProxy() => (global::RoslynAot.RoslynFacade.RoslynObjectProxy)(object)this;
        public global::RoslynAot.Abi.ISwitchLabelSyntaxVtbl __RoslynAotGetVtbl() => global::RoslynAot.RoslynFacade.RoslynVtblFactory.GetSwitchLabelSyntaxVtbl(__RoslynAotGetControlVtbl());
        public global::RoslynAot.Abi.IRoslynControlVtbl __RoslynAotGetControlVtbl() => __RoslynAotGetProxy().ControlVtbl;
        public long __RoslynAotGetHandle() => __RoslynAotGetProxy().GetHandle();
        internal static SwitchLabelSyntax __RoslynAotCreateProxy(global::RoslynAot.Abi.IRoslynControlVtbl controlVtbl, long handle) => (SwitchLabelSyntax)(object)global::RoslynAot.RoslynFacade.RoslynObjectProxy.GetOrCreate(controlVtbl, handle);
        [System.Runtime.InteropServices.DynamicInterfaceCastableImplementation]
        [System.Runtime.InteropServices.Guid("031269d1-d2f7-534e-95bd-1b223f1e2f29")]
        internal partial interface __RoslynAotImplementation : SwitchLabelSyntax
        {
        }
    }
}
