//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("d9ad1b59-8964-5ff3-bca8-eb80a273e017")]
public partial interface IAwaitExpressionInfoVtbl
{

    [PreserveSig]
    int AwaitExpressionInfo_Equals_88f8f46b(
        long receiver,
        long other,
        out int result
    );

    [PreserveSig]
    int AwaitExpressionInfo_GetHashCode(
        long receiver,
        out int result
    );

    [PreserveSig]
    int AwaitExpressionInfo_get_IsDynamic(
        long receiver,
        out int result
    );
}
