//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("dce65f71-92d3-5cb2-96be-f9de95f8c685")]
public partial interface IExplicitInterfaceSpecifierSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int ExplicitInterfaceSpecifierSyntax_Accept_3270a616(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ExplicitInterfaceSpecifierSyntax_Update(
        long receiver,
        long name,
        long dotToken,
        out long result
    );

    [PreserveSig]
    int ExplicitInterfaceSpecifierSyntax_WithDotToken(
        long receiver,
        long dotToken,
        out long result
    );

    [PreserveSig]
    int ExplicitInterfaceSpecifierSyntax_WithName(
        long receiver,
        long name,
        out long result
    );

    [PreserveSig]
    int ExplicitInterfaceSpecifierSyntax_get_DotToken(
        long receiver,
        out long result
    );
}
