//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("0ed0c2e5-a2a6-5a2f-a7fc-89b386bcf589")]
public partial interface IExternAliasDirectiveSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int ExternAliasDirectiveSyntax_Accept_e690c4bd(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_Update(
        long receiver,
        long externKeyword,
        long aliasKeyword,
        long identifier,
        long semicolonToken,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_WithAliasKeyword(
        long receiver,
        long aliasKeyword,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_WithExternKeyword(
        long receiver,
        long externKeyword,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_WithIdentifier(
        long receiver,
        long identifier,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_WithSemicolonToken(
        long receiver,
        long semicolonToken,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_get_AliasKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_get_ExternKeyword(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_get_Identifier(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ExternAliasDirectiveSyntax_get_SemicolonToken(
        long receiver,
        out long result
    );
}
