//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("c64d76ee-41d9-547a-9d15-f842cfa6ee1f")]
public partial interface IInterpolationSyntaxVtbl : IInterpolatedStringContentSyntaxVtbl
{

    [PreserveSig]
    int InterpolationSyntax_Accept_25b8842b(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int InterpolationSyntax_Update(
        long receiver,
        long openBraceToken,
        long expression,
        long alignmentClause,
        long formatClause,
        long closeBraceToken,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_WithAlignmentClause(
        long receiver,
        long alignmentClause,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_WithCloseBraceToken(
        long receiver,
        long closeBraceToken,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_WithExpression(
        long receiver,
        long expression,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_WithFormatClause(
        long receiver,
        long formatClause,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_WithOpenBraceToken(
        long receiver,
        long openBraceToken,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_get_AlignmentClause(
        long receiver,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_get_CloseBraceToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_get_FormatClause(
        long receiver,
        out long result
    );

    [PreserveSig]
    int InterpolationSyntax_get_OpenBraceToken(
        long receiver,
        out long result
    );
}
