//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("15f4ed3b-0eaf-50e1-bf5d-16a86780cbd5")]
public partial interface IParameterListSyntaxVtbl : IBaseParameterListSyntaxVtbl
{

    [PreserveSig]
    int ParameterListSyntax_Accept_605b09cb(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int ParameterListSyntax_WithCloseParenToken(
        long receiver,
        long closeParenToken,
        out long result
    );

    [PreserveSig]
    int ParameterListSyntax_WithOpenParenToken(
        long receiver,
        long openParenToken,
        out long result
    );

    [PreserveSig]
    int ParameterListSyntax_get_CloseParenToken(
        long receiver,
        out long result
    );

    [PreserveSig]
    int ParameterListSyntax_get_OpenParenToken(
        long receiver,
        out long result
    );
}
