//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("afcf61ef-0901-556f-ba64-52837c388288")]
public partial interface ISelectOrGroupClauseSyntaxVtbl : ICSharpSyntaxNodeVtbl
{
}
