//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("6de73205-c0bc-5d58-867c-6332cbf0573f")]
public partial interface ISourceProductionContextVtbl
{

    [PreserveSig]
    int SourceProductionContext_ReportDiagnostic(
        long receiver,
        long diagnostic
    );
}
