//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("dd519e5f-b19b-5d7a-ba43-164f37b74bbd")]
public partial interface ISyntaxTreeVtbl
{

    [PreserveSig]
    int SyntaxTree_ToString(
        long receiver,
        nint buffer,
        int bufferLength,
        out int requiredLength
    );
}
