//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace AnalyzeAot.Abi;

[GeneratedComInterface]
[Guid("f645a763-6627-55ac-a4eb-4eb302d7e8d8")]
public partial interface IVariableDeclaratorSyntaxVtbl : ICSharpSyntaxNodeVtbl
{

    [PreserveSig]
    int VariableDeclaratorSyntax_Accept_bc2b842b(
        long receiver,
        long visitor
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_Update(
        long receiver,
        long identifier,
        long argumentList,
        long initializer,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_WithArgumentList(
        long receiver,
        long argumentList,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_WithIdentifier(
        long receiver,
        long identifier,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_WithInitializer(
        long receiver,
        long initializer,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_get_ArgumentList(
        long receiver,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_get_Identifier(
        long receiver,
        out long result
    );

    [PreserveSig]
    int VariableDeclaratorSyntax_get_Initializer(
        long receiver,
        out long result
    );
}
